### ISSUE TITLE
Any unicode overloads of the string related functions possible?

### ISSUE THREAD

**Issue by jeanga** [Neargye/magic_enum#1]
Hi,

Is there anything preventing the various std::string&std::string_view functions to be overloaded with their wstring&wstring_view equivalent?

This library is a very welcome and useful addition ! Thanks!
Jean

**Comment by jeanga** [comment]
I have implemented basic wide strings functionality in the attached file.

[magic_enum.zip](https://github.com/Neargye/magic_enum/files/3058829/magic_enum.zip)


I hope you find it useful.
Jean
PS: Only tested with MSVC 2019

**Comment by Neargye** [comment]
Ok, I understand your request, I add on weekend new overloads for name's functions.

**Comment by Neargye** [comment]
In C++17/20 we have `string, wstring, u8string , u16string, u32string`, so I think should not add overloads for each type of string.
You can convert the result to any desired string type.

**Comment by jeanga** [comment]
While I agree that std::string can be converted to any other string, I would loose the benefits constexpr machinery in magic_enum. 
This library was really promising though. I whish you all the best with it.
Thanks!

**Comment by Neargye** [comment]
Library returns string_view, you can construct wstring_view in compile time.

**Comment by Neargye** [comment]
@jeanga  in what cases do you need wstring?

**Comment by jeanga** [comment]
I develop on Windows and Windows is natively Unicode and wchar_t (aka WCHAR) based for its APIs. So, most of the strings I manipulate are UTF16. std::wstring is my default choice for strings and convert all the things is a pain and slower.

**Comment by Neargye** [comment]
Use this dev version [magic_enum.zip](https://github.com/Neargye/magic_enum/files/3107065/magic_enum.zip)

You can change `using string = std::string_view;` to `using string = std::wstring_view;`

Later I add more friendly api to change string type.

**Comment by jeanga** [comment]
Great! 
I will test this and report here.
Thank you!
