### ISSUE TITLE
the magic_enum::enum_names does not work when try to assign to global variable

### ISSUE THREAD

**Issue by braindevices** [Neargye/magic_enum#10]
`magic_enum::enum_names` seems only works in function.
```
enum class Color : int { RED = -10, BLUE = 0, GREEN = 10 };
constexpr auto color_names0 = magic_enum::enum_names<Color>();
int main()
{
constexpr auto color_names = magic_enum::enum_names<Color>();
std::cout << color_names0[0] << "\n"; // this give out some random string
std::cout << color_names[0] << "\n"; // this is fine. 
}
```

**Comment by Neargye** [comment]
Hi @braindevices , you use clang?
I check this issues on msvc and gcc all ok, clang give out some random string.

**Comment by braindevices** [comment]
yes! Both clang7 and clang8 has the problem.

**Comment by Neargye** [comment]
Thanks for these issues, I need some time to debug this.

**Comment by Neargye** [comment]
Now, unfortunately, I can only advise you not to use global variables, apparently, some features of the clan are affecting.

**Comment by braindevices** [comment]
The problem seems happens when you try to return string_view in constexpr. When you return string_view inside function it is OK. But when you return string_view in global it gives something like `top level ...`
But if  you directly return string literal, this won't happens.

**Comment by Neargye** [comment]
I will try copy string in `static_string` like this https://gcc.godbolt.org/z/CAyzmA. Maybe this can help.

**Comment by Neargye** [comment]
Hi @braindevices  please check dev branch, on my test issues is fixed.

dev: https://wandbox.org/permlink/fmUqnAwxsthepRtZ
master: https://wandbox.org/permlink/2mShvcCgQbP9PffX

**Comment by Neargye** [comment]
Add fix to master, all test pass.
