### ISSUE TITLE
I'm thinking about testing the "Static reflection for enums" library in a Qt project, is there anything that might be incompatible?

### ISSUE THREAD

**Issue by carlosdelfino** [Neargye/magic_enum#100]
I'm writing a new application and I'm in need of features that this library offers, but I'm afraid there is some incompatibility with Qt.

Has anyone tested it, would you have any recommendations?

I'm using `C++1z` (C++17)

Grateful.

**Comment by Neargye** [comment]
This library works with native C ++ enums with some [limitations](https://github.com/Neargye/magic_enum/blob/master/doc/limitations.md).

**Comment by carlosdelfino** [comment]
considering https://github.com/Neargye/magic_enum/blob/master/doc/limitations.md, I haven't seen anything that might surprise me with Qt.

**Comment by Neargye** [comment]
I, too, can not yet imagine possible problems. If there are any problem, open the issues
