### ISSUE TITLE
There is some magic for enum without case sensitive.

### ISSUE THREAD

**Issue by carlosdelfino** [Neargye/magic_enum#101]

**Comment by Neargye** [comment]
Could you describe your question in a little more detail?

**Comment by carlosdelfino** [comment]
I have a metadata file where the user of my application describes some objects, in each line there is a description of the object separated by commas where I separate the patterns using Regexp, some fields in this line are representations of an enum, for example:

```
NET Block,null,Bloco de Barramento Generico,[[2-10|I]|[1|N||10]]
BLOCK,null,Bloco Generico,[[2-10|I]|[1-3|O]]

OR,gate/OR_ANSI.svg,Porta AND,[[2-*|I]|[1|O]]
AND,gate/AND_ANSI.svg,Porta AND,[[2-*|I]|[1|O]]
Buffer,gate/Buffer_ANSI.svg,Buffer,[[1|I]|[1|O]]

Gated SR, flipflop/Gated_SR_flip-flop.svg, Flip Flop Gated SR,[[1|I|S]|[2|I|R]|[3|I|E]|[1|O|Q]|[2|O|Q|1]]
```

In the fourth field:

```
[[2-10|I]|[1|N||10]]
[[2-10|I]|[1-3|O]]

[[2-*|I]|[1|O]]
[[2-*|I]|[1|O]]
[[1|I]|[1|O]]

[[1|I|S]|[2|I|R]|[3|I|E]|[1|O|Q]|[2|O|Q|1]]

```
Where there is I, O, Z or N, the user may mistakenly use lowercase, so I wanted to avoid this problem already directly in the library, I could use booster or another algorithm, but I wanted to have this option already inside magic_enum.

If the user writes 'O' or 'o', 'Z' or 'z' would not be a problem, as magic_enum itself would treat it as case insensitive, and would convert everything to uppercase.

**Comment by Neargye** [comment]
you can pass a functor when casting or comparison, example
```cpp
enum_cast<Color>("blue", [](char lhs, char rhs) { return std::tolower(lhs) == std::tolower(rhs); }).value() == Color::BLUE
```

**Comment by viniciusferrao** [comment]
> you can pass a functor when casting or comparison, example
> 
> ```c++
> enum_cast<Color>("blue", [](char lhs, char rhs) { return std::tolower(lhs) == std::tolower(rhs); }).value() == Color::BLUE
> ```

Sorry but I don't get it. I think I have a similar issue here, but in my case I would like to do case insensitive conversions from `string` to `enum`.

As an example:

```
void OS::setDistro(std::string_view distro) {
    if (distro == "rhel") {
        setDistro(OS::Distro::RHEL);
        return;
    }

    if (distro == "ol") {
        setDistro(OS::Distro::OL);
        return;
    }

    if (bistro == "rocky) {
        setDistro(OS::Distro::Rocky);
        return;
    }

    throw std::runtime_error(
            fmt::format("Unsupported Distribution: {}", distro));
}
```

It would be much more cleaner if I could just do:

```
void OS::setDistro(std::string_view distro) {
    if (const auto& rv = magic_insentive_enum::enum_cast<Distro>(distro))
        setDistro(rv.value());
    else
        throw std::runtime_error(
                fmt::format("Unsupported Distribution: {}", distro));
}
```

With the second implementation adding a new distribution is easy as adding a new field on my `enum class` declaration.

You may argue that I should just store the `enum`s with proper capitalization, but I'm using `magic_enum` heavily and it would break the `enum` to `string` conversion for user output.

If there's a `magic_enum::enum_insensitive_cast` would be awesome.

Thank you.

**EDIT:** Just found [this](https://github.com/Neargye/magic_enum/pull/139). So it's just a matter of time to get the functionality.

**Comment by Neargye** [comment]
I think you already have an option.
```cpp
void OS::setDistro(std::string_view distro) {
    if (const auto& rv = magic_enum::enum_cast<Distro>(distro, [](char lhs, char rhs) { return std::tolower(lhs) == std::tolower(rhs); }))
        setDistro(rv.value());
    else
        throw std::runtime_error(fmt::format("Unsupported Distribution: {}", distro));
}
```

**Comment by viniciusferrao** [comment]
Thanks @Neargye that done the work perfectly. I'll wait the "syntactic sugar" feature on the next release, but for now your trick is great.

I don't get it exactly yet, but I'll figure out what's happening.

**Comment by Neargye** [comment]
You can use like this. @viniciusferrao 
```cpp
void OS::setDistro(std::string_view distro) {
    if (const auto& rv = magic_enum::enum_cast<Distro>(distro, magic_enum::case_insensitive))
        setDistro(rv.value());
    else
        throw std::runtime_error(fmt::format("Unsupported Distribution: {}", distro));
}
```

**Comment by viniciusferrao** [comment]
I'm looking forward to this. Just waiting the next release of magic_enum.
