### ISSUE TITLE
Odd behaviour with VS 2017

### ISSUE THREAD

**Issue by kerim371** [Neargye/magic_enum#103]
Hi,

I use magic enum in my project and I noticed very odd behaviour in the following context.
Let suppose in my `h5core_enum.h` I have:
```cpp
enum class ContainerAttributes : unsigned{
  ContainerType = 1
};

inline constexpr auto& cnt_attrs =
    magic_enum::enum_names<h5geo::detail::ContainerAttributes>();
inline constexpr auto ContainerType = magic_enum::enum_name<h5geo::detail::ContainerAttributes::ContainerType>();

enum class SeisAttributes : unsigned{
  Domain = 1,
  SeisDataType = 2
};

inline constexpr auto& seis_attrs =
    magic_enum::enum_names<h5geo::detail::SeisAttributes>();
inline constexpr auto Domain = magic_enum::enum_name<h5geo::detail::SeisAttributes::Domain>();
inline constexpr auto SeisDataType = magic_enum::enum_name<h5geo::detail::SeisAttributes::SeisDataType>();
```
and then I use `ContainerType` variable and `Domain` variable.
Using Travis CI I noticed that some of my tests fail with VS 2017 as `Domain` variable contains `ContainerType` string instead of `Domain`. All other platforms Ubuntu with Clang and GCC, OSX and my local Windows 2019 works as expected.

If I change every `magic_enum::enum_name<Enum::Val>()` to `magic_enum::enum_name(Enum::Val)` then the problem is gone:
```cpp
enum class ContainerAttributes : unsigned{
  ContainerType = 1
};

inline constexpr auto& cnt_attrs =
    magic_enum::enum_names<h5geo::detail::ContainerAttributes>();
inline constexpr auto ContainerType = magic_enum::enum_name(h5geo::detail::ContainerAttributes::ContainerType);

enum class SeisAttributes : unsigned{
  Domain = 1,
  SeisDataType = 2
};

inline constexpr auto& seis_attrs =
    magic_enum::enum_names<h5geo::detail::SeisAttributes>();
inline constexpr auto Domain = magic_enum::enum_name(h5geo::detail::SeisAttributes::Domain);
inline constexpr auto SeisDataType = magic_enum::enum_name(h5geo::detail::SeisAttributes::SeisDataType);
```

If you have some idea why it behaves like that please share. Also what is the right way of using `magic_enum::enum_name` in this case?

Here is my [project's commit with successive tests](https://github.com/tierra-colada/h5geo/tree/59c756b92103ddcf7ebcb9005350a9215aaa43ba) and this is a [commit when tests fail](https://github.com/tierra-colada/h5geo/tree/68bf238bbd569bfd2de272ab368a495783ad8a0c)

**Comment by Neargye** [comment]
Unfortunately, this is an internal bug for the vs 2017.

**Comment by kerim371** [comment]
Thank you, good to know
