### ISSUE TITLE
Iterate names & values at compile time

### ISSUE THREAD

**Issue by rpatters1** [Neargye/magic_enum#106]
I would like to iterate the names & values at compile time. In particular, I would like to use `values[i]` as a template parameter, which the compiler refuses:

```c++
template<int N> foo;

constexpr std::size_t count = magic_enum::enum_count<ENUM>();
constexpr auto& values = magic_enum::enum_values<ENUM>();
constexpr auto& names = magic_enum::enum_names<ENUM>();

for (int i=0; i<count; i++)
{
   foo<values[i]> bar; // error Non-type template argument is not a constant expression
}
```

The [refl-cpp](https://github.com/veselink1/refl-cpp) compile-time reflection library has a construction that would allow something like this:

```c++
for_each(values, [&](auto v)
{
   foo<v> bar;  //no error, if this existed in magic_enum
}
```

My question is whether such a method of iterating already exists. If not, would you be interested in a pull request that implements it? (I haven't tried to do it yet, but maybe I can get something working.)

**Comment by rpatters1** [comment]
Answering my own question, I found a [website](https://artificial-mind.net/blog/2020/10/31/constexpr-for) that had rather good solution:

```c++
// from https://artificial-mind.net/blog/2020/10/31/constexpr-for
template <auto Start, auto End, auto Inc, class F>
constexpr void constexpr_for(F&& f)
{
    if constexpr (Start < End)
    {
        f(std::integral_constant<decltype(Start), Start>());
        constexpr_for<Start + Inc, End, Inc>(f);
    }
}
```
So now we can iterate the original example as follows.

```c++
template<int N> foo;

constexpr std::size_t count = magic_enum::enum_count<ENUM>();
constexpr auto& values = magic_enum::enum_values<ENUM>();
constexpr auto& names = magic_enum::enum_names<ENUM>();

constexpr_for<0, count-1, 1>([&](auto i)
{
   foo<values[i]> bar; // no error; works
});
```

I'm not sure there is any reason to work this into `magic-enum` since some sort of `constexpr for` is apparently proposed as a language enhancement.

**Comment by rpatters1** [comment]
Well, rats. The above solution works on XCode/GCC but not on Visual Studio 2019. So here's a variant that works on both.

```c++
template<typename ENUM, int X>
struct foo
{
   int _foo;
   foo(int N) : _foo(N){}
};

constexpr std::size_t count = magic_enum::enum_count<ENUM>();
constexpr auto& values = magic_enum::enum_values<ENUM>();
constexpr auto& names = magic_enum::enum_names<ENUM>();

constexpr_for<0, count-1, 1>([&](auto i)
{
   foo<ENUM, i> bar(values[i]); // no error; works on both XCode and VS2019
});
```
This version is slightly more fragile than the previous, because it doesn't allow for multiple `enum` constants with the same value (aliases). However, neither does `magic-enum` so it's good enough for me.

**Comment by Neargye** [comment]
Push update at master

Now this work on VS2019
```cpp
template <typename ENUM, ENUM X> struct foo {};

constexpr_for<0, magic_enum::enum_count<Color>(), 1>([](auto i) {
  [[maybe_unused]] foo<Color, magic_enum::enum_value<Color, i>()> bar{};
});
```

**Comment by rpatters1** [comment]
This works well. Thanks.
