### ISSUE TITLE
Limitations with big enum values, especially with Vulkan

### ISSUE THREAD

**Issue by s9w** [Neargye/magic_enum#108]
Hey Magicians!
Until recently, I happily (and naively!) used magic_enum with my Vulkan application. One update later and it doesn't compile anymore. I think the reason was this [line from a commit in April](https://github.com/Neargye/magic_enum/commit/5b282dd4e86a7874427760e6ce6d1f684b9f1b30#diff-672cedb46a42e43a8461d9bcec5b1616fe537c2d9451544b896786f632324f7dR404).

Now since then I read up about the limits of this library and found out that it puts very hard limits on default min/max values, and even on what's possible. The latter maxing out at 2^16. Vulkan uses fantastically large enum values right up to 2^31-1 (`VkFormat` for example).

So this won't work according to the documentation, which is fine I guess. But I have to ask: This seemed to have worked just fine when the check wasn't enforced correctly. So does this have some severe drawbacks to use? If I comment out that line... I have to admit I have no idea how this magic works, but I never ran into any trouble beforehand.

All good if this stays the way it is. ~Sebastian

**Comment by Neargye** [comment]
These errors mean that the library did not reflect all the enum values.
I can add an option to turn off errors.

**Comment by s9w** [comment]
Oh I see, so it can't actually reflect values above those limits. I probably never used such enums by chance then. But that error should absolutely stay if I got this right. So I rest my case.
