### ISSUE TITLE
Change documentation from "string" to "string_view" 

### ISSUE THREAD

**Issue by parsley72** [Neargye/magic_enum#109]
I was confused trying to use `enum_name` then covert to a C string using `.c_str()` until I realised it returns a `string_view`. Documentation should be changed to give the correct type.

**Comment by Neargye** [comment]
Could you tell me exactly where the inaccuracy in the documentation is?

You can use the `data()` because it returns a string_view to a null-terminated static `char[]`.

**Comment by parsley72** [comment]
- Under Features it says "Enum value to string".
- Under Examples it says "Enum value to string".
- Example code uses `auto`.

I handled it by wrapping in a `string` and using `.c_str()` because `data()` is only safe if you know the `string_view` is null-terminated and that's not explicity stated. I'm not arguing against the implementation, just that I had to read the code before I could figure out what it was doing.

**Comment by Neargye** [comment]
"to string" - this is indicated ideologically, the exact type is already an implementation detail. you can also look at the documentation, it contains all the inappropriate types and guarantees. https://github.com/Neargye/magic_enum/blob/master/doc/reference.md

`auto c1_name = std::string{magic_enum::enum_name(c1)};` - you can write like this if you need a correct type, according to the AAA rule https://herbsutter.com/2013/08/12/gotw-94-solution-aaa-style-almost-always-auto/

**Comment by parsley72** [comment]
I was just making the point that this confused me, not that the implementation is wrong. The documentation could be clearer - if it was I wouldn't have run into this problem.

**Comment by Neargye** [comment]
I'll update readme soon
