### ISSUE TITLE
Is it necessary to add different conversion functions to enum?

### ISSUE THREAD

**Issue by Neargye** [Neargye/magic_enum#11]
Now we have
1. `std::optional<E> enum_cast(std::string_view value) noexcept`
2. `std::optional<E> enum_cast(std::underlying_type_t<E> value) noexcept`

Is it necessary to add the following functions? Will it be useful to someone?
1. `std::optional<E> enum_from_string_nothrow(std::string_view value) noexcept`
2. `std::optional<E> enum_from_string_nocase_nothrow(std::string_view value) noexcept`
3. `E enum_from_string(std::string_view value)`
4. `E enum_from_string_nocase(std::string_view value)`
5. `std::optional<E> enum_from_integral_nothrow(std::underlying_type_t<E> value) noexcept`
6. `E enum_from_integral(std::underlying_type_t<E> value)`
7. `E enum_from_integral_unchecked(std::underlying_type_t<E> value)`
See https://github.com/Neargye/magic_enum/tree/from_functions

**Comment by alexkaratarakis** [comment]
Is
`std::optional<E> enum_from_string_nothrow(std::string_view value) noexcept` 
different from:
`std::optional<E> enum_cast(std::string_view value) noexcept`
?

**Comment by Neargye** [comment]
No. 
`std::optional<E> enum_cast(std::string_view value) noexcept` == `std::optional<E> enum_from_string_nothrow(std::string_view value) noexcept`
`std::optional<E> enum_cast(std::underlying_type_t<E> value) noexcept` == `std::optional<E> enum_from_integral_nothrow(std::underlying_type_t<E> value) noexcept`
