### ISSUE TITLE
XCode Analyze Error

### ISSUE THREAD

**Issue by rpatters1** [Neargye/magic_enum#111]
I've been running XCode Analyze on my code. This is a fairly effective tool for finding hidden bugs that cause memory errors. I have the following function (simplified for the example):

```c++
template<typename ENUM>
void AddEnumeratedType(const std::string& nameSpace)
{
   constexpr std::size_t count = magic_enum::enum_count<ENUM>();
   constexpr auto& names = magic_enum::enum_names<ENUM>();

   constexpr_for<0, count, 1>([&](auto i)
   {
      const auto pName = names[i].data(); // this line generates Analyze warning message
      // does some work with pName
   });
}
```

The warning message is

```
Called C++ object pointer is uninitialized (within a call to 'AddEnumeratedType')
```

If I replace the initialization of `pName` with a hard-coded string like `"123"` then the warning goes away. That makes me thing that Analyze somehow thinks there is a code path in which the value being returned by the `data()` method hasn't been initialized.

This may not be a problem at all. It could be that the `constexpr` magic in `magic-enum` is confusing it. But I thought I would at least raise the issue in case there is an obvious fix. (I looked but didn't see it.)

**Comment by Neargye** [comment]
Maybe try `constexpr auto names`, remove the reference, this will not change the behavior, but it may fix the warning.

**Comment by rpatters1** [comment]
That solved the issue. Thanks. I'm wondering if the documentation should be updated. The reference always looked strange to me, but I dutifully copied the example in the documentation.

**Comment by Neargye** [comment]
will update examples and documentation
