### ISSUE TITLE
Some function parameters pass string objects that involve copying

### ISSUE THREAD

**Issue by ghost** [Neargye/magic_enum#114]
Normally we would write const string_view& str

**Comment by Neargye** [comment]
https://quuxplusone.github.io/blog/2021/11/09/pass-string-view-by-value/

**Comment by ghost** [comment]
> https://quuxplusone.github.io/blog/2021/11/09/pass-string-view-by-value/

The article is just something in writing.
The speed of actually transmitting the address is much greater than the speed of copying the data.

**Comment by Neargye** [comment]
could you please show me where in the library string data is being copied?

string_view - this is the address and size of the string data.
