### ISSUE TITLE
If enum has negative number,not work.

### ISSUE THREAD

**Issue by sukeyisme** [Neargye/magic_enum#115]
magic_enum::enum_cast<T>(enum_value) not work.

**Comment by Neargye** [comment]
Could you please show an example of an enum that does not work?

**Comment by sukeyisme** [comment]
enum class Test {
  kTest1 = -100,
  kTest2 = -102,
  kTest3 = -200,
};

auto test = magic_enum::enum_cast<Test>(-200);
    if (test == Test::kTest3) {
      std::cout << "test" << std::endl;
    }

**Comment by Neargye** [comment]
https://github.com/Neargye/magic_enum/blob/master/doc/limitations.md

* Enum value must be in range [MAGIC_ENUM_RANGE_MIN, MAGIC_ENUM_RANGE_MAX].
* By default MAGIC_ENUM_RANGE_MIN = -128, MAGIC_ENUM_RANGE_MAX = 128.

**Comment by sukeyisme** [comment]
But my enum is not in range ,any workaround?

**Comment by isgursoy** [comment]
https://github.com/Neargye/magic_enum/blob/master/include/magic_enum.hpp#L123

**Comment by isgursoy** [comment]
> But my enum is not in range ,any workaround?

https://github.com/Neargye/magic_enum/blob/master/include/magic_enum.hpp#L123
