### ISSUE TITLE
Example of bit-oriented enum

### ISSUE THREAD

**Issue by rpatters1** [Neargye/magic_enum#116]
In a recent issue thread you mentioned a bit-oriented api that greatly reduced the max span of numbers magic_enum needs to search. Is there an example somewhere of how to use this?

Thanks

**Comment by Neargye** [comment]
Here basic enum bit-flag example 
https://github.com/Neargye/magic_enum/blob/master/example/enum_flag_example.cpp

**Comment by rpatters1** [comment]
Thank you! I hope I didn't miss that link in the doc pages.
