### ISSUE TITLE
Compilation does not fail if enum value is out of range

### ISSUE THREAD

**Issue by bialasjaroslaw** [Neargye/magic_enum#117]
I have noticed that for some enums I have compilation fail (which is good, as I don't want to check if any code has some issues with wrong min/max specification for enum values one by one), but for others it is not complaining at all.

It seems that this happens only if there is a missing enum of value `MAGIC_ENUM_RANGE_MAX+1`

This is fairly representative example of the code that should fail to compile but it does not. Line that is commented out will fail, but if it's missing everything seems fine.

```c++
#include <fmt/printf.h>
#include <magic_enum.hpp>

enum class integer{
    value = 1,
    ok_value = 128, // OK
    // fail_value = 129, // Fail
    dont_care_value = 130, // Don't care
};

int main()
{
    fmt::print("integer value {} and name: {}\n", static_cast<int>(integer::value), 
        magic_enum::enum_name(integer::value));
}
```

[godbolt link](https://godbolt.org/z/1fEaxoecW)

Is it even possible at this stage of language evolution to do such thing?

**Comment by Neargye** [comment]
We can check, for example, the next 10 values (MAGIC_ENUM_RANGE_MAX+1 ... MAGIC_ENUM_RANGE_MAX+10), but unfortunately, this will not change the situation much.

**Comment by bialasjaroslaw** [comment]
I was afraid of that. Well at least I am aware of that now. I thought that it will be mentioned somewhere, so I checked readme/limitations at least twice. Maybe it is a good idea to mention this somewhere? 

Anyway, thank you for your work. I really appreciate it and have been using `magic_enum` since I heard of it in many of projects that I am involved in.

**Comment by Neargye** [comment]
In general, if you want, I would be happy with the PR.
Perhaps a fresh look at the documentation will help make it better.

**Comment by mciruzzi1** [comment]
Hey! Is it still possible to work on this issue?

**Comment by Neargye** [comment]
On it issue, it is necessary to update the documentation. @mciruzzi1
