### ISSUE TITLE
Question about flag-based api

### ISSUE THREAD

**Issue by rpatters1** [Neargye/magic_enum#118]
I am trying to reduce compile-time requirements of memory and time for my project. I have some power-of-2-based `enums` that span a pretty wide interval. I was hoping that using the `flags` api would use much fewer resources, but I can't see any difference in behavior. I still have to set `/constexpr:depth` and `/constexpr:steps` quite high before it will compile in Visual Studio 2022.

Here is an outline of my code:

```c++
enum A {A1 = 8192, A2=32};

// static_assert in magic_enum.hpp fires if this isn't here
namespace magic_enum::customize {
   template <>
   struct enum_range<A> {
      static constexpr int min = 32;
      static constexpr int max = 8192;
   };
} // namespace magic_enum

// this function exists solely to return a value equal to the enumerated type value
template<int I>
static int __magic_enum_return_i() { return I; }

template<typename ENUM>
void AddEnumeratedTypeFlags()
{
   constexpr std::size_t count = magic_enum::flags::enum_count<ENUM>();
   constexpr auto names = magic_enum::flags::enum_names<ENUM>();

   constexpr_for<0, count, 1>([&](auto i)
   {
      //run-time function that processes each enum value
      Process(names[i].data(), &__magic_enum_return_i<magic_enum::flags::enum_value<ENUM, i>()>);
   });
}

void MyCode()
{
   AddEnumeratedTypeFlags<A>();
}
```

I'm wondering if there is something further I need to do to get the benefit of the `flags` api.

**Comment by Neargye** [comment]
`magic_enum::customize` - not using in flags  api.

https://godbolt.org/z/Y9Ecfd36f

```cpp
#include <iostream>
#include <magic_enum.hpp>

enum A { A1 = 8192, A2 = 32 };

void Process(std::string_view n)
{
  std::cout << n << std::endl;
}

template <auto Start, auto End, auto Inc, class F>
constexpr void constexpr_for(F&& f) {
  if constexpr (Start < End) {
    f(std::integral_constant<decltype(Start), Start>());
    constexpr_for<Start + Inc, End, Inc>(f);
  }
}
template<typename ENUM>
void AddEnumeratedTypeFlags()
{
  constexpr std::size_t count = magic_enum::flags::enum_count<ENUM>();
  constexpr auto names = magic_enum::flags::enum_names<ENUM>();

  constexpr_for<0, count, 1>([&](auto i)
    {
      //run-time function that processes each enum value
      Process(names[i].data());
    });
}

int main() {
  AddEnumeratedTypeFlags<A>();

  return 0;
}
```

**Comment by rpatters1** [comment]
Suppose I modify `Process` as follows:

```c++
void Process(std::string_view n, int x)
{
  std::cout << n << ": " << x << std::endl;
}
```

and the call as follows:

```c++
      Process(names[i].data(), magic_enum::flags::enum_value<ENUM, i>());
```

Then I get a `static_assert` error on line `936` of `magic_enum.hpp`:

```c++
static_assert(I < detail::count_v<D>, "magic_enum::flags::enum_value out of range.");
```

I can fix this error by adding in `magic_enum::customize` but then (as you noted) I get no advantage from the `flags` api.

**Comment by Neargye** [comment]
I will check this

**Comment by rpatters1** [comment]
Thanks. FWIW: I just tried commenting out the `static_assert` line, and my real code compiled and ran correctly.

**Comment by rpatters1** [comment]
It looks to me like there is a `true` missing in the `static_assert` on line `936`:

```c++
static_assert(I < detail::count_v<D, true>, "magic_enum::flags::enum_value out of range.");
```

Also possibly the line above as well, but I'm not sure about that since it isn't causing an error for me.

**Comment by Neargye** [comment]
Push fix in master

**Comment by rpatters1** [comment]
Thank you.

**Comment by Neargye** [comment]
Also add missing tests.

**Comment by rpatters1** [comment]
I realize it may be too late for this, but might it have been more convenient to implement the `flags` ui as an optional template parameter rather than a separate namespace? I.e.:

```c++
template <typname ENUM, bool IsFlags = false>
magic_enum::enum_names...
template <typname ENUM, bool IsFlags = false>
magic_enum::enum_count...
```
etc.

Much of your internal code seems to work this way. I ended up having to put in ugly lambdas into my code to avoid code duplication.

**Comment by Neargye** [comment]
This can be taken out in a separate issue.
The main problem is that not all api will work this way, for example `enum_name(E value);`
