### ISSUE TITLE
Combining flags ui and non-flags ui in the same processing routine

### ISSUE THREAD

**Issue by rpatters1** [Neargye/magic_enum#119]
I am running a project that processes many enums to load them as read-only properties into a Lua context using [`LuaBridge`](https://github.com/vinniefalco/LuaBridge). With your help I was able to get the `flags` ui working for my power-of-2 enums, and it greatly reduces the compile time and memory requirements for compiling them.

Now I would like to use a single routine to process either type of enum. So far, this is working, where `Process` is a runtime function that adds the property to `LuaBridge`:

```c++
template<typename ENUM, bool IsFlags = false>
void AddEnumeratedType(const std::string& nameSpace, lua_State *l)
{
   constexpr std::size_t count = []()
            {
               if constexpr (IsFlags)
                  return magic_enum::flags::enum_count<ENUM>();
               else
                  return magic_enum::enum_count<ENUM>();
            }();
   constexpr auto names = []()
            {
               if constexpr (IsFlags)
                  return magic_enum::flags::enum_names<ENUM>();
               else
                  return magic_enum::enum_names<ENUM>();
            }();
   constexpr_for<0, count, 1>([&](auto i)
   {
      if constexpr (IsFlags)
         Process(names[i].data(), magic_enum::flags::enum_value<ENUM, i>());
      else
         Process(names[i].data(), magic_enum::enum_value<ENUM, i>());
   });
}
```

But it's a little ugly. The main requirement is that only the `flags` or the non-`flags` path should be evaluated. Not both. It seems like if there were a combined ui that took both `ENUM` and `IsFlags` as template parameters then the code would be a lot nicer. (Many of your internal routines do this.)

(hypothetical code with `combined` namespace, but just for clarity in this example)

```c++
template<typename ENUM, bool IsFlags = false>
void AddEnumeratedType(const std::string& nameSpace, lua_State *l)
{
   constexpr std::size_t count = magic_enum::combined::enum_count<ENUM, IsFlags>();
   constexpr auto names = magic_enum::combined::enum_names<ENUM, IsFlags>();

   constexpr_for<0, count, 1>([&](auto i)
   {
      Process(names[i].data(), magic_enum::combined::enum_value<ENUM, IsFlags, i>());
   });
}
```

The version I have now is working, so this is definitely just a nice-to-have kind of suggestion. Also, perhaps there is a cleaner way to do it that I haven't thought of, using the existing code in `magic_enum`. Either way, it's a fantastic tool for reflecting enums.

**Comment by Neargye** [comment]
```cpp
enum A {A1 = 8192, A2=32};

template <>
magic_enum::customize::is_flags_enum<A> : std::true_type {};
```
How about adding this?

```cpp
// Inside lib
template <typename E>
[[nodiscard]] constexpr auto enum_count() noexcept -> detail::enable_if_enum_t<E, std::size_t> {
  return detail::count_v<E, customize::is_flags_enum<E>::value>;
}
```

**Comment by rpatters1** [comment]
That would work for me. Would I continue to use `magic_enum::names` and `magic_enum::enum_value` as before? If so, your solution is cleaner than an extra template parameter.

**Comment by Neargye** [comment]
yes, in fact, there will be the same tempalte parameter, it will just be hidden inside the api, you will set the flag for the whole enum

**Comment by rpatters1** [comment]
That sounds like an ideal solution.

**Comment by Neargye** [comment]
Please test https://github.com/Neargye/magic_enum/pull/120

I added auto-detection for the enum flags, but I'm sure it covers all cases.

**Comment by rpatters1** [comment]
I've tested #120, and it compiles and runs my test suite correctly on both macOS and Windows. (I no longer have to blow out the `constexpr` steps/depth on Windows.) I also benchmarked my build times and couldn't measure any differences attributable to the change. I like this solution for flags a lot.

**Comment by Neargye** [comment]
I need a little more time to clean it all up, but I think the basic concept and api will remain the same.

**Comment by Neargye** [comment]
@rpatters1 A bit late, new features have been added

`enum_cast` and `enum_flags_cast`

```cpp
enum_name(color::red | color::blue | color::gree) -> ""
enum_cast(color::red | color::blue | color::green) -> std::nullopt; 

enum_flags_name(color::red | color::blue | color::gree) -> "red|blue|gree"
enum_flags_cast(color::red | color::blue | color::green) -> color::red | color::blue | color::green; 
```

Also work "combined" API

```cpp
enum_name<as_flags<false>>(color::red | color::blue | color::gree) -> ""
enum_cast<as_flags<false>>(color::red | color::blue | color::green) -> std::nullopt; 

enum_name<as_flags<true>>(color::red | color::blue | color::gree) -> "red|blue|gree"
enum_cast<as_flags<true>>(color::red | color::blue | color::green) -> color::red | color::blue | color::green; 
```

**Comment by rpatters1** [comment]
Thank you for the heads up. I check this repo periodically for updates.
