### ISSUE TITLE
How to deal with 'invalid/empty' enum values?

### ISSUE THREAD

**Issue by Cleroth** [Neargye/magic_enum#121]
Often times I feel the need to have an enum value for empty/invalid. The problem with this is it gets counted for `enum_count` and `enum_values`, etc...

Currently I'm doing something like:

```cpp
enum class Foo : std::uint8_t
{
	Zero,
	One,​
	Invalid = std::numeric_limits<std::underlying_type_t<Foo>>::max(),
};
```

Is there a better way to do this?

**Comment by Neargye** [comment]
You can try like this.
```
enum class Foo : std::uint8_t
{
	Zero,
	One,​
	Invalid,
};

    template <>
    struct magic_enum::customize::enum_range<Foo> {
      static constexpr int min =  (int)Foo::Zero;
      static constexpr int max = (int)Foo::Invalid;
    };
```

**Comment by Cleroth** [comment]
`enum_count<Foo>()` and `enum_values<Foo>().size()` still return `3` with that.

**Comment by Neargye** [comment]
Sory, need `count-1`
```cpp
template <>
struct magic_enum::customize::enum_range<Foo> {
  static constexpr int min = static_cast<int>(Foo::Zero);
  static constexpr int max = static_cast<int>(Foo::Invalid) - 1;
};
 ```
 Or try this
 ```cpp
 template <>
constexpr std::string_view magic_enum::customize::enum_name<Foo>(Foo value) noexcept {
  switch (value) {
    case Foo::Invalid:
    case Foo::InvalidAnother:
      return "-1"; // Invalid name.
    default:
      return {}; // Empty string for default.
  }
}
 ```

**Comment by Cleroth** [comment]
That's certainly an alternative, but it seems to have more disadvantages:

1. it's just more code
2. it needs to be in the global namespace, so it will likely end up separate from the actual enum declaration
3. the value of invalid will keep changing as you add more enum values
4. it actually still triggers an "out of range" compilation error due to some check added recently to the lib

I've just ended up doing `Invalid = std::uint8_t(-1);` since most enums won't go past that anyway. It's still not completely safe but yea...

**Comment by Neargye** [comment]
`Invalid = std::uint8_t(-1);` Yes, I really think this is the best way.
