### ISSUE TITLE
Visual Studio 2022 IntelliSense Error E0095

### ISSUE THREAD

**Issue by rpatters1** [Neargye/magic_enum#122]
I am encountering a strange IntelliSense error in Visual Studio 2022. This is not actually causing the compile to fail or any other issues that I can see. And even weirder, when I click on the error to view the line of code, the error disappears. (I haven't figured out what makes it reappear.) The line of code is line 183:

```c++
  char chars_[N + 1];
```

The error message is here:

<img width="735" alt="Screen Shot 2022-01-24 at 11 19 14 AM" src="https://user-images.githubusercontent.com/11542367/150833001-5d7c2571-b531-4c83-89f0-c20fde973bab.png">

For all I know it is a bug in VS 2022. But I thought I would report it in case it is something you wish to know about.

**Comment by Neargye** [comment]
Can suppress some kind of warning or error help?

**Comment by rpatters1** [comment]
Oh, sure. As I say, the message comes and goes and it's IntelliSense. It doesn't affect the build. I was wondering if maybe there should be a `static_assert` on `N` that limits it to whatever is a generous but reasonable value.

**Comment by rpatters1** [comment]
FWIW: As an experiment I added a `static_assert` to force `N` less than `UINT16_MAX`. So far the error hasn't appeared. (But it's too soon to say if that made a difference.)

**Comment by Neargye** [comment]
an interesting workaround, I thought about the concert, but so far we have C++17.  if this solution will be ok, I can add it myself or you can do PR if you want.

**Comment by rpatters1** [comment]
Ok I'll submit a PR.
