### ISSUE TITLE
How this lib works?

### ISSUE THREAD

**Issue by bitnick10** [Neargye/magic_enum#124]
Why this lib can get enum name as string since C++ doesn't have reflection yet?What's the magic?

**Comment by Neargye** [comment]
This library uses a compiler-specific hack (based on `__PRETTY_FUNCTION__` / `__FUNCSIG__`), which works on Clang >= 5, MSVC >= 15.3 and GCC >= 9.

We go through the given interval range and find all the enumerations with a name, this will be their count. Read more about limitations https://github.com/Neargye/magic_enum/blob/master/doc/limitations.md

Many more about this hack in this post https://taylorconor.com/blog/enum-reflection.

**Comment by ZXShady** [comment]
You can read more here

https://blog.rink.nu/2023/02/12/behind-the-magic-of-magic_enum/
