### ISSUE TITLE
Apply an anonymous enum to the enum_type_name function?

### ISSUE THREAD

**Issue by v1nh1shungry** [Neargye/magic_enum#128]
I found that when I apply an anonymous enum to the `magic_enum::enum_type_name` function, it will compile successfully and return `<unnamed enum>`. Here's my code.

```cpp
#include "magic_enum.hpp"
#include <iostream>

enum { RED, GREEN, BLUE };

int main()
{
    auto color = RED;
    std::cout << magic_enum::enum_type_name<decltype(color)>();    // <unnamed enum>
    return 0;
}
```

My environment:

* MSYS2 MINGW64
* g++ version: g++.exe (Rev8, Built by MSYS2 project) 11.2.0

Also I got `<unnamed-enum-RED>` when running the same code in Visual Studio 2019.

And, I also got a [gobolt link](https://godbolt.org/z/Wza9asrE6).

I wonder if this is a feature or a bug. However, I guess it is a bug because I notice that in your code:

```cpp
// Returns type name of enum.
template <typename E>
[[nodiscard]] constexpr auto enum_type_name() noexcept -> detail::enable_if_enum_t<E, string_view> {
constexpr string_view name = detail::type_name_v<std::decay_t<E>>;
  static_assert(name.size() > 0, "Enum type does not have a name.");    // here

  return name;
}
```

It seems that you want to get a compilation failure when the enum type doesn't have a name, that is, an an anonymous enum type. And this makes sense. Otherwise I wonder what kind of enum doesn't have a name.

Did I misunderstand anything? Thanks for your time.

**Comment by v1nh1shungry** [comment]
If this is a bug, it may be fixed by simply using `pretty_name` like this:

```cpp
template <typename E>
constexpr auto n() noexcept {
  static_assert(is_enum_v<E>, "magic_enum::detail::n requires enum type.");
#if defined(MAGIC_ENUM_SUPPORTED) && MAGIC_ENUM_SUPPORTED
#  if defined(__clang__) || defined(__GNUC__)
    constexpr auto name = pretty_name({__PRETTY_FUNCTION__, sizeof(__PRETTY_FUNCTION__) - 2});
#  elif defined(_MSC_VER)
    constexpr auto name = pretty_name({__FUNCSIG__, sizeof(__FUNCSIG__) - 17});
#  endif
    return static_string<name.size()>{name};
#else
  return string_view{}; // Unsupported compiler.
#endif
}
```

Yeah, just like what you did in `template <typename E, E e> constexpr auto n() noexcept` function.

**Comment by Neargye** [comment]
Yes, it looks like a bug, if you want, you can do PR, or I'll fix it later.

**Comment by v1nh1shungry** [comment]
Sure, I'm glad to do PR. Thanks for replying.
