### ISSUE TITLE
for-each friendly magic_enum::enum_values 

### ISSUE THREAD

**Issue by Warwolt** [Neargye/magic_enum#130]
Been using magic_enum a little and I absolutely _love_ it. Adds so much ergonomy to enum classes that is missing in plain C++. One thing I'm missing however is the ability to declare something like the following code:

```C++
auto colors = magic_enum::enum_values<Color>();
for (Color color : colors) {
    // do something with color
}
```

Since the array that is returned from `enum_values` doesn't have a size that matches the number of enum variants, the iterator above will not only construct the valid variants but also a bunch of invalid enum instances. Considering that `magic_enum::enum_count` exists, I would've expected the `enum_values` function to be able to construct only the necessary values in the array (i.e I would've expected `auto` here to be equal to `std::array<Color, magic_enum::enum_count<Color>()>`).

Is there any limitation that makes this infeasible? Otherwise I think it would be a considerable improvement to an already fantastic library.

**Comment by Warwolt** [comment]
For context I got this helper function working, so in theory this should be doable as part of the library I think.

```C++
    template <typename T>
    constexpr auto enum_values() -> std::array<T, magic_enum::enum_count<T>()> {
        return []<std::size_t... Is>(std::index_sequence<Is...>) {
            return std::array<T, magic_enum::enum_count<T>()>{
                std::get<Is>(magic_enum::enum_values<T>())...
            };
        }(std::make_index_sequence<magic_enum::enum_count<T>()>());
    }
```

**Comment by Warwolt** [comment]
For context I got this helper function working, so in theory this should be doable as part of the library I think.

```C++
namespace test_util {
    template <typename T>
    constexpr auto enum_values() -> std::array<T, magic_enum::enum_count<T>()> {
        return []<std::size_t... Is>(std::index_sequence<Is...>) {
            return std::array<T, magic_enum::enum_count<T>()>{
                std::get<Is>(magic_enum::enum_values<T>())...
            };
        }(std::make_index_sequence<magic_enum::enum_count<T>()>());
    }
} // namespace test_util
```

**Comment by Neargye** [comment]
Could you show an example where `magic_enum::enum_values()` does not work as it should?
https://github.com/Neargye/magic_enum/blob/master/doc/reference.md#enum_values

**Comment by Neargye** [comment]
https://wandbox.org/permlink/UhvbONpIyJHkHdeY

```cpp
enum class Color : int { RED = -10, BLUE = 0, GREEN = 10 };

int main() {
  // 1
  constexpr auto colors = magic_enum::enum_values<Color>();
  for (Color c : colors) {
    std::cout << magic_enum::enum_name(c) << " ";
  }
  std::cout << std::endl;
  // 2
  for (Color c : magic_enum::enum_values<Color>()) {
    std::cout << magic_enum::enum_name(c) << " ";
  }
  std::cout << std::endl;
  // 3
  std::cout << "magic_enum::enum_values<Color>().size() = " << magic_enum::enum_values<Color>().size();
  std::cout << " magic_enum::enum_count<Color>() = " << magic_enum::enum_count<Color>();
  std::cout << std::endl;

  return 0;
}
```
Output:
```
RED BLUE GREEN 
RED BLUE GREEN 
magic_enum::enum_values<Color>().size() = 3 magic_enum::enum_count<Color>() = 3
```

**Comment by Neargye** [comment]
https://wandbox.org/permlink/QphdouUiPLTG3OTh

```cpp
test_util::enum_values<Color>() == magic_enum::enum_values<Color>() // true
```

**Comment by Warwolt** [comment]
Hm, I think I must've done something else wrong and gotten confused by intellisense reporting the constexpr as giving an array of size 256. Not quite sure what was the problem here. I tried replacing some tests with just `magic_enum::enum_values` instead of the util with a std::cout printout of the values that gave the expected behavior. 

Closing this as a user error :)
