### ISSUE TITLE
compile error

### ISSUE THREAD

**Issue by HerrDingenz** [Neargye/magic_enum#133]
After updating to the latest code i get a compile error in Visual Studio 2022:

in line 939 it says:

`throw std::logic_error{"magic_enum::enum_fuse accepts only in-range enum values"};`

this causes a
`error C2760: syntax error: '{' was unexpected here; expected 'expression'`

however .. changing the {} to () in that line of code and including stdexcept at the top of the file fixes that.

**Comment by HerrDingenz** [comment]
i forgot to mention my project is set to for c++20 and not c++17

**Comment by Neargye** [comment]
Fixed in master

**Comment by HerrDingenz** [comment]
works .. thank you :)
