### ISSUE TITLE
vcpkg does not seem to install the header file

### ISSUE THREAD

**Issue by tester0077** [Neargye/magic_enum#134]
Just tried to use the current version by installing it via vcpkg, but that process did not install the header file, which is all I expected to need.

After trying to install the package, I ended up with 2 directories in the vcpk tree - for x86
D:\pkg\vcpkg\installed\x86-windows\share\
magic-enum
magic_enum

vcpkg only knows about
magic-enum               0.7.3#1          Header-only C++17 library provides static reflection for enums, work with .

I have no idea whether that is referring to this package or not, but something seems of.
The project looks very inviting and useful, so I will work with the header file directly - at least for now.

**Comment by Neargye** [comment]
This is official package in vcpkg https://github.com/microsoft/vcpkg/tree/master/ports/magic-enum

So installing magic-enum 0.7.3#1 is ok.

**Comment by tester0077** [comment]
Just installing a vcpkg for other packages has installed the code (libs and headers) without any further work on my part other than setting up the path to the files needed, but it does not seem to work for this package.
Perhaps I should raise the issue with the vcpkg team?

**Comment by Neargye** [comment]
If you check with the developers and tell them the result, I will be grateful to you. I just don't use vcpkg.

**Comment by tester0077** [comment]
Done
