### ISSUE TITLE
How to use magic_enum

### ISSUE THREAD

**Issue by tester0077** [Neargye/magic_enum#135]
suppose I have declared a struct
#include "magic_enum.hpp"
enum class eImageRotationEnums
{
  eIrNoRotation =   0, // "no rotation"
  eIrRotateRight, // "rotate right, CW"
  eIrRotateLeft, // "rotate left, CCW"
  eIrFlipHorizontal, // "FlipHorizontal"
};
and define a function:     wxImage       RotateImage( wxImage inputImage, int rotation );

and want to use one specific value as a function argument ---V
m_Image1 = RotateImage( m_Image1, eImageRotationEnums::eIrRotateRight );

What do I need to do - cast or?? - to make the MSVC 22019 compiler accept the call.
I have tried ISO C++17/20 without luck

One attempt:
 m_Image1 = RotateImage( m_Image1, magic_enum::enum_cast<eImageRotationEnums>(eImageRotationEnums::eIrRotateRight);
and several variations.
None were acceptable.

Is this even possible or is this one of the 'limitations' about using it with(in) a class?

**Comment by Neargye** [comment]
try
`m_Image1 = RotateImage( m_Image1, magic_enum::enum_integer(eImageRotationEnums::eIrRotateRight) );`

**Comment by tester0077** [comment]
Thank you, that dis the trick.
I thought I tried that but must have been some mistake with all of the typing :-)

Glad I asked
