### ISSUE TITLE
magic enum static_asserts on an enum value of 129

### ISSUE THREAD

**Issue by CarloWood** [Neargye/magic_enum#136]
I ran into this with 0.7.2, then upgraded to 0.7.3. Both have this issue. I use git and tags, so this was with tag "v0.7.3".

Consider the following snippet:

```
#include <magic_enum.hpp>

enum Errors {
  SE_EKEYREJECTED = 129,
};

std::string to_string(Errors error)
{
  auto sv = magic_enum::enum_name(error);
  return std::string{sv};
}

int main()
{
}
```

When compiling, you get:

```
include/magic_enum.hpp:407:21: error: static assertion failed: magic_enum::enum_range detects enum value larger than max range size.
  407 |       static_assert(!is_valid<E, value<E, lhs + 1, IsFlags>(0)>(), "magic_enum::enum_range detects enum value larger than max range size.");
include/magic_enum.hpp:407:21: note: ‘! magic_enum::detail::is_valid<Errors, SE_EKEYREJECTED>()’ evaluates to false
```

Using a value of 128 or 130 compiles fine. Having other enums in there does not make a difference.

**Comment by CarloWood** [comment]
I should have mentioned I am using `g++ version 11.2.0` or `clang++ version 13.0.1` on linux. Using `-std=c++17` or `-std=c++20` - both give the same error.

**Comment by Neargye** [comment]
This was an attempt to check that the enum values ​​were out of range, but it was too non-obvious, so it was removed. You can try the latest version from the master.

**Comment by CarloWood** [comment]
I do not get that.  Surely it is a bug / undesirable that you can't compile a program that uses a value of 129 for an enum?

**Comment by CarloWood** [comment]
Are you saying that there is something out of range (not working)?

**Comment by Neargye** [comment]
This library has [limitations ](https://github.com/Neargye/magic_enum/blob/master/doc/limitations.md),  if some values out of range it's will not work.

**Comment by CarloWood** [comment]
Ah! Thank you for the clarification. I had not realized there were limitations (or did forget I read that). The reason I came to the conclusion that it had to be a bug is because values larger than 129 work fine (the original code has values between 5 and 133 I believe). If you change the 129 into 130 or larger, it compiles fine (I did not check if it also worked). Of course I realized that 129 is very close to 128 - but I dismissed this as a "magic" value because then you expect a range [-128, 127] and 128 being the first that fails ;). At least then all values fit precisely in a byte - or unsigned char.

**Comment by CarloWood** [comment]
Using master wouldn't have fixed things I understand. So I just applied this patch to my code:
https://github.com/CarloWood/dbus-task/commit/cb76f886017b941b009bbf80a2840b72e4d0e874

Thank you!

**Comment by alexkaratarakis** [comment]
> This was an attempt to check that the enum values ​​were out of range, but it was too non-obvious, so it was removed. You can try the latest version from the master.

The check caught a real bug in this case. I think there is value in having it.

> has values between 5 and 133

The alternative here would have been that values 129-133 were silently ignored which would be hard to debug.

It is definitely not a perfect check, but it can catch a subset of issues cheaply.

Would a clearer error message about what went wrong and how to fix it help here?

**Comment by Neargye** [comment]
@alexkaratarakis I'm still thinking about a better option

**Comment by CarloWood** [comment]
I think the error should happen, but for all values that are too large. Not only one that is 1 larger than the maximum. And the error given probably should contain a link to a website that explains it?

**Comment by Neargye** [comment]
> all values that are too large

Unfortunately that's not possible, that's the problem.
