### ISSUE TITLE
reduce memory footprint

### ISSUE THREAD

**Issue by Trass3r** [Neargye/magic_enum#14]
For a runtime value to string conversion it generates a list of strings and a string_view map. In theory data usage could be reduced to 1/4 by using an index plus a small size squeezed into a uint32_t instead of string_view if the strings could be forced into a contiguous array.

**Comment by Neargye** [comment]
Check https://github.com/Neargye/magic_enum/commit/55dc79600dc84aa5f35c411751426d80e93c730f

New header for test https://github.com/Neargye/magic_enum/blob/55dc79600dc84aa5f35c411751426d80e93c730f/include/magic_enum.hpp

**Comment by Neargye** [comment]
https://godbolt.org/z/ySzprC
vs
https://godbolt.org/z/N_NIa3
vs
https://godbolt.org/z/4GKZZ4

Which is better for you?

**Comment by Trass3r** [comment]
So # 2 is using zero-terminated strings and # 3 a separate string size array using smaller base types. Which amounts to the same size cost in this common case of short enum names.
Edit: Ah no, # 3 is more of a sparsity optimization?!

If you actually use the size the code is a bit different of course:
https://godbolt.org/z/hn1eHK vs https://godbolt.org/z/XyFkeA

**Comment by Neargye** [comment]
3 only an array of valid string sizes and store array index.

To be honest, I don’t think that these optimizations will win much for real code. So I can’t decide what to choose 2 or 3

**Comment by Neargye** [comment]
range = 128
1 sizeof(std::string_view) * range // 16 * range 
2 sizeof(const char*) * range // 8 * range 
3 sizeof(uint16_t) * range  + sizeof(std::string_view) * count // 2 * range   + 16 * count

For small enums 3 better, for big 2. These are rough calculations, correct me if I am wrong.

**Comment by Trass3r** [comment]
I don't think 3 is worth it, you should optimize the min/max macro values as a user anyway (e.g. to use non-negative enum values).
2 could come in handy for passing them to APIs not accepting a length parameter and does save half the memory but introduces strlen() calls in other cases. I guess it could still be a good solution.

**Comment by Neargye** [comment]
How about this https://godbolt.org/z/iGvmls

**Comment by Neargye** [comment]
If sparsity -> Compresses size and indexes
Else -> Finds min and max, and uses the full range 

For InstrInfo min = 0, max = 124. 

This looks like a good optimization for msvc, before it optimized the worst.

**Comment by Neargye** [comment]
In dev branch final version, I think merge it's on master.

**Comment by Neargye** [comment]
Fix in master
