### ISSUE TITLE
make typesafe enum_fuse

### ISSUE THREAD

**Issue by schaumb** [Neargye/magic_enum#143]
Currently it can be write the following:

```
enum class C1 { a, b, c };
enum class C2 { a, b, c };
switch(enum_fuse(C1::a, C2::b)) {
case enum_fuse(C2::a, C1::b):
   // oops it handled
   break;
}
```

So enum fuse is not recognize the parameter types.

It can be made typesafe with the following trick:

```
template<typename ... enums>
constexpr auto enum_fuse(enums ... vars) {
    enum class Enum : std::uintmax_t {}
    std::uintmax_t val = old_enum_fuse(vars...);
    return static_cast<Enum>(val);
}
```

**Comment by pavelkryukov** [comment]
Looks great – it constructs a Cartesian product enum of N enums in compile time! It should solve problems of fused enums # mismatch too. And we can remove `+ 1` trick.

**Comment by pavelkryukov** [comment]
Sadly it looks like UB:

```
C++ standard 5.2.9 Static cast [expr.static.cast] paragraph 7

A value of integral or enumeration type can be explicitly converted to an enumeration type. The value is unchanged if the original value is within the range of the enumeration values (7.2). Otherwise, the resulting enumeration value is unspecified / undefined (since C++17).
```

**Comment by Neargye** [comment]
This is a good idea, but then the switch on such an enum will be hit warning C4063.

**Comment by pavelkryukov** [comment]
Was about to post the same:

```c++
/Users/runner/work/magic_enum/magic_enum/test/test.cpp:1033:10: error: case value not in enumerated type 'std::__1::optional<Enum>::value_type' (aka 'Enum') [-Werror,-Wswitch]
    case magic_enum::enum_fuse(Color::BLUE, Directions::Down).value():
         ^
```

@Neargye but it is not an UB up to your knowledge?

**Comment by Neargye** [comment]
AIK, not UB, I investigate how suppress this warning.

**Comment by pavelkryukov** [comment]
```diff
-    enum class Enum : std::uintmax_t {}
+    enum class Enum : std::uintmax_t;
```

This hides the fact enum has no values from compilers.

But Visual Studio does not like `switch/case` over incomplete enums. It is a different warning (C4064), maybe safer to be ignored/disabled than C4063.
