### ISSUE TITLE
enum_values cannot get values if enum is forward declaration

### ISSUE THREAD

**Issue by zelon** [Neargye/magic_enum#15]
If a enum is forward declaration, enum_values() cannot get valid values.

`enum class MyEnum;`
`for (auto enum_value : magic_enum::enum_values<MyEnum>()) {`
`  // some print statement`
`}`

Is there any solution?

**Comment by zelon** [comment]
How about add a static_assert like below?

`template <typename E, typename D = detail::enable_if_enum_t<E>>`
`[[nodiscard]] constexpr auto enum_values() noexcept {`
`  static_assert(detail::check_enum_v<E, D>, "magic_enum::enum_values requires enum type.");`
`  constexpr auto values = detail::values_v<D>;`
` static_assert(values.size() > 0, "magic_enum::enum_values requires enum implementation.");`
`  return values;`
`}`

**Comment by Neargye** [comment]
Hi, could you please try new version from master?

**Comment by Neargye** [comment]
@zelon I think it's good idea, I will add this.

**Comment by Neargye** [comment]
Unfortunately, enum can't reflect if the enum is a forward declaration.
Add static_assert to check this case. Thx @zelon.

**Comment by zelon** [comment]
It works fine. Thx @Neargye
