### ISSUE TITLE
create enable/disable customization point for enum values

### ISSUE THREAD

**Issue by schaumb** [Neargye/magic_enum#153]
@Neargye idea for the [enum disable feature](https://github.com/Neargye/magic_enum/pull/138#issuecomment-1057295127) is to create another customization point:

```
template <>
constexpr bool magic_enum::customize::enum_valid<Color>(Color value) noexcept {
  return value == Color::RED ? false : true;
}
```

This needs an implementation

**Comment by schaumb** [comment]
https://github.com/Neargye/magic_enum/compare/master...schaumb:enable_disable_customization_point?expand=1

I made it (without documentation).

This has some caveat
---

The library user can think that if an enum has not a representant value, can be enabled with this.

```
enum class A : int {
    _0 = 0, 
    _1, 
    _2, 
    _4 = 4
}

template <>
constexpr bool magic_enum::customize::enum_is_valid<A>(A value) noexcept {
    switch (value) {
      case static_cast<A>(1):
      case static_cast<A>(2):
      case static_cast<A>(3):
      case static_cast<A>(4):
        return true;
      default:
        return false;
    }
};
```
`A` enum with value `3` is not valid.

---

The library user can be used a combination of customization which can be controversial:

```
template <>
constexpr bool magic_enum::customize::enum_is_valid<A>(A value) noexcept {
    return value != A::_1;
}

template <>
constexpr string_view magic_enum::customize::enum_name<A>(A value) noexcept {
    return value == A::_1 ? "I want this name for _1" : "";
}
```

So `A::_1` name is not what it set, it has no name.

**Comment by Neargye** [comment]
I would add a static asserter that if an enum is valid it should have a name. It's fixing caveat I thinks

**Comment by Neargye** [comment]
I thought about how to combine this into 1 function and make it convenient, perhaps something like
```cpp
template <>
constexpr optional<string_view> magic_enum::customize::enum_name<Color>(Color value) noexcept {
  switch (value) {
    case Color::RED:
      return "the red color";
    case Color::BLUE:
      return magic_enum::customize::default;
    case Color::GREEN:
     return magic_enum::customize::invalid;
  }
  return magic_enum::customize::default;
}
```

```cpp
namespace magic_enum::customize {
inline constexpr auto default  = string_view{};
inline constexpr auto invalid  = optional<string_view>{};
}
```

**Comment by Neargye** [comment]
Or
```cpp
template <>
constexpr customize_t  magic_enum::customize::enum_name<Color>(Color value) noexcept {
  switch (value) {
    case Color::RED:
      return "the red color";
    case Color::BLUE:
      return magic_enum::customize::default;
    case Color::GREEN:
     return magic_enum::customize::state::invalid;
  }
  return magic_enum::customize::state::default;
}
```

```cpp
namespace magic_enum::customize {
enum class state  { default , invalid };
using customize_t = variant<string_view, state>;
}
```

**Comment by schaumb** [comment]
I like this idea (last one, with `variant`).
`default` is not a C++ keyword? Can be used like that?
And what about backward compatibility?

**Comment by Neargye** [comment]
There are two options for backward compatibility
* Make a major release with broken backward compatibility
* Make a check for the return type, if the string is the old behavior, if the variant is the new one.
