### ISSUE TITLE
Error message in macOS with latest version

### ISSUE THREAD

**Issue by rpatters1** [Neargye/magic_enum#155]
When I compile with macOS XCode, the following message occurs on line 921:

```c++
//error: 'value' is unavailable: introduced in macOS 10.13
return (hash.value() << detail::log2(enum_count<E>() + 1)) | (index.value() + 1);
```

I can increase my minimum target to macOS 10.13 and presumably make it work, but I would like not to have to do that. Is there some way this code could be made optional? For now I am sticking with an earlier branch of `magic_enum`.

**Comment by Neargye** [comment]
please check master version

**Comment by rpatters1** [comment]
It doesn't appear to make a difference, except now the error occurs on line 920. (It's the same line, though.)
