### ISSUE TITLE
Enum in template not working with Clang

### ISSUE THREAD

**Issue by dominicpoeschko** [Neargye/magic_enum#164]
Enums in templated structs do not work on Clang but do work in GCC

Works:
`enum class E1{aa, bb};`

Does not Work:
```
template<typename>
struct xx{
enum class E{aa, bb};
};
```

Godbold link with example

https://godbolt.org/z/x3e4rKT89

**Comment by schaumb** [comment]
weird. It's probably a compiler optimization bug.

If you reference one of the enum value, the problem is gone.
https://godbolt.org/z/cj5b1ETxc

**Comment by schaumb** [comment]
gcc works, only clang optimize out enum names:

```
template<typename T, T v>
auto n() {
    return std::string_view{__PRETTY_FUNCTION__};
}

std::cout << n<E2, static_cast<E2>(0)>();  // writes: auto n() [T = xx<int>::E, v = (xx<int>::E)0]
```

**Comment by schaumb** [comment]
I think it is a limitation because of the compiler  optimization.  It is need to mentioned on the Limitation page.
