### ISSUE TITLE
clang 5 build is broken

### ISSUE THREAD

**Issue by schaumb** [Neargye/magic_enum#165]
https://godbolt.org/z/aMod7MoKK

[This commit caused](https://github.com/Neargye/magic_enum/pull/137/files#diff-672cedb46a42e43a8461d9bcec5b1616fe537c2d9451544b896786f632324f7dR517) which helped me for gcc8.

I think curly braces can be solve the problem (or explicit array template parameters)

**Comment by Neargye** [comment]
Are you using clang 5?

**Comment by schaumb** [comment]
No, just the "Limitations" says It's working with clang 5.

**Comment by Neargye** [comment]
Oh yes, I think it's time to up version.

**Comment by Neargye** [comment]
will be up to clang-6
