### ISSUE TITLE
magic_enum::enum_name() doesn't work for boolean enum

### ISSUE THREAD

**Issue by pholat** [Neargye/magic_enum#171]
Compiling with c++17 on GCC 11.2.0:

``` c++17
#include <iostream>
#include "magic_enum/include/magic_enum.hpp"

enum class Test : bool {
    Yay, Nay
};

int main()
{
    Test val = Test::Yay;
    std::cout << magic_enum::enum_name(val) << std::endl;
}
```

will result in: 

`magic_enum/include/magic_enum.hpp:355:42: error: use of an operand of type ‘bool’ in ‘operator++’ is forbidden in C++17`

This is caused by log2 implementation. 

The cleanest solution would be to add override for bool:
``` c++
constexpr bool log2(bool  /*value*/) noexcept {
  return true;
}
```
Please let me know if it's acceptable so I would create a PR with it, or would you like different solution.

**Comment by Neargye** [comment]
fix in master, thanks for report
