### ISSUE TITLE
Feature Request: automatic istream operators

### ISSUE THREAD

**Issue by breyerml** [Neargye/magic_enum#177]
Would it be possible to automatically generate `operator>>` together with `operator<<`? 

Background: we are using cxxopts to parse command-line arguments.
cxxopts supports parsing them directly to enums **if** a corresponding `operator>>` exists.
This is currently unfortunately not the case.
I'm currently using something like:
```cpp
std::istream& operator>>(std::istream& in, enum_type& value) {
    std::string str;
    in >> str;

    auto opt_value = magic_enum::enum_cast<kernel_type>(str);
    if (opt_value.has_value()) {
        value = opt_value.value();
    } else {
        in.setstate(std::ios::failbit);
    }

    return in;
}
```
Would it be possible to add something like this?

**Comment by Neargye** [comment]
I think I can add, but to be honest, I'm not fully able to correctly handle errors inside operator>>. Is ` in.setstate(std::ios::failbit);` enough?

**Comment by breyerml** [comment]
At least setting `in.setstate(std::ios::failbit);` is the only thing done in the canonical implementation of `operator>>` on cppreference (https://en.cppreference.com/w/cpp/language/operators).

**Comment by Neargye** [comment]
add to master namespace magic_enum::istream_operators
