### ISSUE TITLE
linking error

### ISSUE THREAD

**Issue by HerrDingenz** [Neargye/magic_enum#178]
I have 2 projects - a core library and a main project that depends on the core library.
I have to include magic_enum.hpp in both projects and when compiling i get a linking error (LNK2005):

`public: __cdecl magic_enum::detail::default_result_type_lambda<void>::<lambda>::operator()(void)const '::1'::__LINE__Var" (?__LINE__Var@?0???R<lambda>@?$default_result_type_lambda@X@detail@magic_enum@@QEBA@XZ@4JA) already defined in pch.obj`

I figured out that it is this part of the code (lines 794-798):

````
template <typename T = void>
constexpr auto default_result_type_lambda = []() noexcept(std::is_nothrow_default_constructible_v<T>) { return T{}; };

template <>
constexpr auto default_result_type_lambda<void> = []() noexcept {};
````

However, inlining line 798 seems to do the trick.

```
template <>
constexpr inline auto default_result_type_lambda<void> = []() noexcept {};
```

I am not sure if there is another solution to the issue.

**Comment by Neargye** [comment]
Oh, yes `inline` fix this problem

**Comment by Neargye** [comment]
Fix in master, thanks!

**Comment by HerrDingenz** [comment]
You're welcome and thanks :)
