### ISSUE TITLE
signed/unsigned mismatch warning in visual studio 17.2.2 when enum_cast-ing integers to enum-values.

### ISSUE THREAD

**Issue by bamo-gemini** [Neargye/magic_enum#190]
The underlying type of the enum class is int.
See image below. Ask me for details, I can make a simple reproducable case if necessary.

![bilde](https://user-images.githubusercontent.com/35224692/170707469-1cb34b3b-cea5-4f78-962d-d7d106b9a2bc.png)

**Comment by schaumb** [comment]
Hi @bamo-volue ,

Thanks for the issue report.
I can [reproduce](https://godbolt.org/z/czYbaMGn9) the problem. 
I will find a solution shortly.
