### ISSUE TITLE
declaration of 'last' hides global declaration

### ISSUE THREAD

**Issue by johnco3** [Neargye/magic_enum#192]
I found the following warning in my windows build.  Looks like it has not been addressed.  I renamed the inner variable `last` something else to work around the issue.  Note that the vcpkg port also has this issue and vcpkg is not using the latest magic_enum port.

[link to vcpkg issue](https://github.com/microsoft/vcpkg/issues/25045)

```
9>C:\Users\johnc\main\tcdu\include\702\C702Words.h(450): message : see reference to function template instantiation 'std::optional<WordID> magic_enum::enum_cast<WordID>(unsigned int) noexcept' being compiled (compiling source file ..\..\src\702\C702Protocol.cpp)
9>C:\tools\vcpkg\installed\x64-windows\include\magic_enum.hpp(763,44): error C2220: the following warning is treated as an error (compiling source file ..\..\src\702\C702SubSystem.cpp)
9>C:\tools\vcpkg\installed\x64-windows\include\magic_enum.hpp(763,44): warning C4459: declaration of 'last' hides global declaration (compiling source file ..\..\src\702\C702SubSystem.cpp)
9>C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.32.31326\include\chrono(812,32): message : see declaration of 'std::chrono::last' (compiling source file ..\..\src\702\C702SubSystem.cpp)

```

**Comment by Neargye** [comment]
could you specify the version of the library you are using?

**Comment by johnco3** [comment]
not sure from within vcpkg, I perform a git pull before doing a build (so whatever version is at the head in vcpkg as of today).   (edited June 8th 2022) In answer to your question - Verified version in vcpkg is version 8.0.0.  This is 1 commit behind head - i.e. the "Fix compilation error, when including magic_enum after windows.h" commit is not included (which is also a problem, however I manually patched that)

**Comment by Neargye** [comment]
Could you show an example where this error occurs?

**Comment by schaumb** [comment]
I think this restriction is nonsense. This means you cannot name your local (function scoped) variable as you wish, because of an other package, other namespace global variable.

**Comment by Neargye** [comment]
> I think this restriction is nonsense. This means you cannot name your local (function scoped) variable as you wish, because of an other package, other namespace global variable. 

It seems to me that there may be a problem with capturing the lambda context, which is why I would like to see an example.

**Comment by johnco3** [comment]
Sorry for the late response, but I added the detail over in the vcpkg site
https://github.com/microsoft/vcpkg/issues/25045#issuecomment-1150056479

**Comment by Neargye** [comment]
@johnco3 please test master

**Comment by Neargye** [comment]
Will be released, if still presents, please open new issues
