### ISSUE TITLE
VS2022 IntelliSence Error E0095

### ISSUE THREAD

**Issue by twoone-3** [Neargye/magic_enum#198]
```
E0095 Array is too large
 magic_enum\magic_enum.hpp 198
 in class "magic_enum::detail: :static_string<N> [where N=18446744073709551600Ui64]"
 on line:341 Detected during instantiation
```
When I compile the project with VS2022, the compiler reports this error, my compiler option is C++17, but it compiles and runs without problems, I hope you can check the reason.

**Comment by Neargye** [comment]
It's looks like VS problem https://github.com/Neargye/magic_enum/issues/122
I don't know how to fix this inside library/

**Comment by twoone-3** [comment]
but, from #122 I know that he can add `static_assert` to fix this problem.
Why do you say you do not know it？

**Comment by Neargye** [comment]
see https://github.com/Neargye/magic_enum/pull/125

**Comment by doodlum** [comment]
Is there a workaround for now, because commenting out the header to get intellisense is very frustrating.

**Comment by Neargye** [comment]
@doodlum @twoone-3  test master, please

**Comment by twoone-3** [comment]
@Neargye Lucky, I have tested v8.0.0 and master, both them have no problem!!!

**Comment by twoone-3** [comment]
The error is still exist, line 198

**Comment by Neargye** [comment]
I tried something else fix in master, but honestly ran out of ideas.

**Comment by Neargye** [comment]
Did it help in any way?

**Comment by twoone-3** [comment]
I haven't tested it yet, I'll try it now

**Comment by twoone-3** [comment]
It work! Thank you!
