### ISSUE TITLE
IntelliSense very slow after #include <magic_enum.hpp>

### ISSUE THREAD

**Issue by MarkusMiller** [Neargye/magic_enum#207]
Hello,

I just stumbled across the issue that IntelliSense somehow stopped working smoothly after including magic_enum.hpp. I noticed this already last week in another cpp-File but couldn't see any reason, why that happened. It also was only present in that file. I just created a new file and included magic_enum.hpp as first header and IntelliSense was slow right after that. It recovers, though, when commenting the header out again. 

Is that just the case for me?

**Comment by vNaonLu** [comment]
the same issue occurs on vscode with C/C++ v1.12.0 extension.

**Comment by Germwalker** [comment]
same issue, intellisense slow after including the header

**Comment by Trass3r** [comment]
The header is heavy on compile-time in general which may be the cause.
#219

**Comment by Neargye** [comment]
@MarkusMiller @Germwalker @vNaonLu  Could you please check how it is now on the latest master?

**Comment by MarkusMiller** [comment]
Will try it in the next days and get back to you

**Comment by Germwalker** [comment]
It's better for me ! Seems to be as transparent as other libs. Thank you !

**Comment by MarkusMiller** [comment]
It seems to work now. Thank you

**Comment by vNaonLu** [comment]
Sorry for the late reply. It works for me now. Thank you.

**Comment by Neargye** [comment]
Will prepare new release with improvements
