### ISSUE TITLE
Example of invalid code compiling

### ISSUE THREAD

**Issue by mlindner** [Neargye/magic_enum#21]
This code should be invalid and shouldn't compile but it does, and even optimizes to have 0 be returned implying the string ":dog" is equal to the enum horse.

https://godbolt.org/z/5UvrpB

Why are we allowed to compare a `enum foo` vs an `optional<enum foo>` with boolean operations.

**Comment by Neargye** [comment]
Hi @mlindner,
1. `magic_enum::enum_cast<animal>(":dog");` return nullopt.
2. std::optional has operator==( const optional<T>& opt, const T& value); see https://en.cppreference.com/w/cpp/utility/optional/operator_cmp
3. Chech example https://wandbox.org/permlink/VmJwn6rndwTGOche, ":dog" is __not equal__ to the enum horse.
