### ISSUE TITLE
When enum is marked with a large integer, the function interface fails

### ISSUE THREAD

**Issue by Unsigned-Long** [Neargye/magic_enum#214]
Look at this example. When **Color::RED** is marked as 20, everything is normal.

```cpp
enum Color : int {
    BLUE = 4, GREEN = 8, RED = 20
};

int main(int argc, char *argv[]) {
    Color color = Color::RED;
    auto color_name = magic_enum::enum_name(color);
    // output: color name is: 'RED'
    std::cout << "color name is: '" << color_name << "'\n";
    return 0;
}
```

But when **Color::RED** is marked as 1000 (a large number), all functions of **magic_enum** will fail.

```cpp
enum Color : int {
    BLUE = 4, GREEN = 8, RED = 1000
};

int main(int argc, char *argv[]) {
    Color color = Color::RED;
    auto color_name = magic_enum::enum_name(color);
    // color_name is an empty string
    // output: color name is: ''
    std::cout << "color name is: '" << color_name << "'\n";
    return 0;
}
```

I want to know whether this is a feature or a bug, because now I need to mark a large number for a member of an **Enum**.

**Comment by BrukerJWD** [comment]
I think this is a documented limitation:

> Enum value must be in range [MAGIC_ENUM_RANGE_MIN, MAGIC_ENUM_RANGE_MAX].
> By default MAGIC_ENUM_RANGE_MIN = -128, MAGIC_ENUM_RANGE_MAX = 128.

see https://github.com/Neargye/magic_enum/blob/master/doc/limitations.md

**Comment by Unsigned-Long** [comment]
OK, this can explain the reason, but the library has set:
```cpp
MAGIC_ENUM_RANGE = (MAGIC_ENUM_RANGE_MAX - MAGIC_ENUM_RANGE_MIN) must be less than UINT16_MAX.
```
So I can't define a large number and a small number at the same time. Also, if I set
```cpp
#define MAGIC_ENUM_RANGE_MIN 0
#define MAGIC_ENUM_RANGE_MAX std::numeric_limits<unsigned short>::max() - 2
```
Then compilation will take a lot of time.

**Comment by BrukerJWD** [comment]
I think the compilation time is the reason to limit the maximum range to 256, yes.
