### ISSUE TITLE
Feature request : enum_cast with fallback value

### ISSUE THREAD

**Issue by samhanic** [Neargye/magic_enum#215]
Hello,
First of all, thanks for the work, this library is really a great improvement over C++ standard enums.

When working with enum_cast, I mostly use has_value() method to set a fallback value when no match have been found.
This pattern is quite repetitive and a shorthand working like this would be great :

```c++
enum class Color { NONE = 0, RED = 2, BLUE = 4, GREEN = 8 };

std::string color_name{"GREEN"};
auto color = magic_enum::enum_cast_with_fallback<Color::NONE>(color_name);
// color -> Color::GREEN

std::string wrong_color_name{"MAGENTA"};
auto wrong_color = magic_enum::enum_cast_with_fallback<Color::NONE>(wrong_color_name);
// wrong_color -> Color::NONE
```

The implementation for this function could look something like:

```c++
template<auto default_value, typename T>
[[nodiscard]] constexpr auto enum_cast_with_fallback(const T & value)
{
  auto tmp = magic_enum::enum_cast<decltype(default_value)>(value);
  if (tmp.has_value()) {
    return tmp.value();
  }
  return default_value;
}
```

**Comment by Neargye** [comment]
optional already provides similar functionality
```cpp
auto c = magic_enum::enum_cast<Color>(value).value_or(Color::NONE);
```

**Comment by samhanic** [comment]
Great, I had not thought about this possibility.

Maybe it means the documentation would benefit from an example of this type (same for the "String to enum value" part of the readme).

**Comment by Neargye** [comment]
Will add example.
