### ISSUE TITLE
No name with enum values over 128

### ISSUE THREAD

**Issue by RBJRBJ** [Neargye/magic_enum#22]
I have an enum like this:
enum QUEUE_ENTRY_TYPE : unsigned int {
	QUEUE_ENTRY_UNKNOWN,
	TRN_GET_PROCESS_LIST = 100,
	TRN_GET_TOP_WINDOWS,
	TRN_GET_PROCESS_WINDOWS = 200,
	TRN_GET_CHILD_WINDOWS,
	TRN_GET_POPUP_WINDOWS = 300,
	TRN_GET_WINDOW_INFO,...

But when I try to get the name with the code below it does not work:
QUEUE_ENTRY_TYPE qet = TRN_GET_CHILD_WINDOWS;
auto qet_name = magic_enum::enum_name(qet);

It only works for values below 128.
In the index() function on line 349 it decides the value is bigger than max_v.
What can I do?

**Comment by Neargye** [comment]
Hi, You can read the limitations at the link https://github.com/Neargye/magic_enum/blob/master/doc/limitations.md

If after reading you have any questions or problems, please write here, it will help to improve the documentation

**Comment by Neargye** [comment]
Update docs
