### ISSUE TITLE
Why GCC8 is not supported?

### ISSUE THREAD

**Issue by BIGGIE27** [Neargye/magic_enum#222]
I'm curious, this is a c++17 library, in theory GCC8 is enough, so why we need GCC9 to use it?

**Comment by Neargye** [comment]
magic_enum use intrinsics - namely `PRETTY_FUNCTION`, on GCC < 9 `PRETTY_FUNCTION` not can get name enum.

**Comment by BIGGIE27** [comment]
I understand, thank you

**Comment by ZXShady** [comment]
Hi, the reason as Neargye said.

the library uses `__PRETTY_FUNCTION__` to print the enum names

```cpp
template<auto E>
auto name()
{
   return __PRETTY_FUNCTION__;
}
```

with this enum

```cpp
enum class Test {
   A
};
```

doinf `name<Test::A>()` prints `void name() [E = Test::A]` for gcc >= 9

and for `name<Test(1)>()` it prints `void name() [E = (Test)1]`
while gcc < 9 always prints

`void name() [E = 0]` 

so magic enum cannot really differentiate between valid enum members and invalid ones if it always prints out a number.
