### ISSUE TITLE
Unexpected behavior of enum_for_each for bitmasked enums

### ISSUE THREAD

**Issue by cr545l** [Neargye/magic_enum#225]
```
enum EnumTest
{
	A = 0,
	B = 1 << 0,
	C = 1 << 1,
	D = 1 << 2,
	E = 1 << 3,
	F = 1 << 4,
	G = 1 << 5,
	H = 1 << 6,
	I = 1 << 7,
	J = 1 << 8,
	K = 1 << 9,
	L = B | C | E | G,
};
std::string result="";

magic_enum::enum_for_each<EnumTest>([&](EnumTest t) {
	std::string n = std::string(magic_enum::enum_name(t));
	result.append(n);
});

printf("%s", result.c_str());
```

```
ABCDEFGLHI
```

J and K are missing and the order is mixed

```
enum EnumTest
{
	A = 0,
	B = 1 << 0,
	C = 1 << 1,
	D = 1 << 2,
	E = 1 << 3,
	F = 1 << 4,
	G = 1 << 5,
	H = 1 << 6,
	I = 1 << 7,
	J = 1 << 8,
	K = 1 << 9,
	// L = B | C | E | G, // <- Remove
};
std::string result="";

magic_enum::enum_for_each<EnumTest>([&](EnumTest t) {
	std::string n = std::string(magic_enum::enum_name(t));
	result.append(n);
});

printf("%s", result.c_str()); 
```

```
BCDEFGHIJK
```
A is missing

**Comment by Neargye** [comment]
Does 'A' count as a flag?

**Comment by cr545l** [comment]
> Does 'A' count as a flag?

A will usually be None flag. Anyway, we found inconsistent results in the above two cases.

**Comment by alexkaratarakis** [comment]
The default range for magic_enum is -128 to 128 (https://github.com/Neargye/magic_enum/blob/master/include/magic_enum.hpp#L100), so it is expected for J, K to be missing in the first example as they are out of range. Can you try expanding the range sufficiently so all values are included? (it may affect enum_for_each's behavior)

**Comment by Neargye** [comment]
Hi,

For enum-flags add is_flags to specialization enum_range for necessary enum type. Specialization of enum_range must be injected in namespace magic_enum::customize.
```cpp
enum class Directions { Up = 1 << 1, Down = 1 << 2, Right = 1 << 3, Left = 1 << 4 };
template <>
struct magic_enum::customize::enum_range<Directions> {
  static constexpr bool is_flags = true;
};
```
If not add `is_flags` then the default range for magic_enum is -128 to 128 see https://github.com/Neargye/magic_enum/blob/master/doc/limitations.md. Also you can force control "flags-behavior", for example
```cpp
magic_enum::enum<as_common<>>(EnumTest::A) -> 'A'
magic_enum::enum<as_flags<>>(EnumTest::A) -> '' // null-string
```

Zero is not flag `A = 0`, aslo are "bits or" `L = B | C | E | G` is not flag. Unfortunately, these libs restrictions.
