### ISSUE TITLE
0.8.2 breaks `enum_name` with custom ranges?

### ISSUE THREAD

**Issue by bkaestner** [Neargye/magic_enum#231]
It seems like the newest optimizations in 0.8.2 break `enum_name` in GCC and Clang. Here's a minimal complete verifiable example:

# MVCE
I've [also prepared a gist ](https://gist.github.com/bkaestner/58f0bfdf7e66aaaa2a373bc662b1c08c).

The MVCE needs the following file structure:

```
CMakeLists.txt
enum.h
enum.cc
magic_enum.hpp
main.cc
main_with_range.cc
```

### CMakeLists.txt
The CMakeLists.txt specifies the language standard and three targets: 

- a `enum` library, which uses `magic_enum` internally but doesn't expose it via its header/interface
- a `mve`, which uses the aforementioned `enum` library, but not the `magic_enum.hpp` header
- a `mve_bad`, which uses the aforementioned `enum` library and `magic_enum.hpp` header as well as `enum_range`
```cmake
cmake_minimum_required(VERSION 3.15)
project (mve LANGUAGES CXX)
set(CMAKE_CXX_STANDARD 17)

option(ENABLE_FIX "Enable MAGIC_ENUM_ENABLE_HASH" OFF)
if(ENABLE_FIX)
    add_compile_definitions(MAGIC_ENUM_ENABLE_HASH)
endif()

add_library(enum STATIC enum.cc)

add_executable(mve main.cc)
target_link_libraries(mve enum)

add_executable(mve_bad main_with_range.cc)
target_link_libraries(mve_bad enum)
```
### enum.h
`enum.h` contains a single enum with values that are outside of `magic_enum`'s default range, i.e. `flag::high` with `500`, as well as a declaration for a `string_view`-yielding function:
```c++
#ifndef EXAMPLE_ENUM_H
#define EXAMPLE_ENUM_H

#include <string_view>

enum class flag
{
    low = 0,
    high = 500,
};

std::string_view to_string(flag);

#endif // EXAMPLE_ENUM_H
```
Note that `magic_enum` is explicitly *not* a
### enum.cc
This file contains a `customize::enum_range` call to work around the known [limitations](https://github.com/Neargye/magic_enum/blob/master/doc/limitations.md). It also contains the implementation of the aforementioned `to_string` function, which calls `magic_enum::enum_name` within the same file:

```c++
#include "enum.h"
#include "magic_enum.hpp"

template <>
struct magic_enum::customize::enum_range<flag>
{
    static constexpr int min = static_cast<int>(flag::low);
    static constexpr int max = static_cast<int>(flag::high);

    static_assert(static_cast<uint64_t>(max) - static_cast<uint64_t>(min) < std::numeric_limits<uint16_t>::max(),
                  "magic_enum only supports names for the uint16_t range.");
};

std::string_view to_string(flag f){
    return magic_enum::enum_name(f);
}
```
### main.cc
Now, this is the "working" case. Both lines return exactly what you would expect:
```c++
#include <iostream>

#include "enum.h"
#include "magic_enum.hpp"

int main() {
    std::cout << to_string(flag::low) << std::endl;  // prints "low", as expected
    std::cout << to_string(flag::high) << std::endl; // prints "high", as expected
}
```
### main_with_range.cc
But as soon as you use `magic_enum::enum_values<enum_type>()`, the customization in the implementation file gets ignored:
```c++
#include <iostream>

#include "enum.h"
#include "magic_enum.hpp"

int main() {
    for (auto f : magic_enum::enum_values<flag>()) {
        std::cout << to_string(f) << std::endl;  // ⚠prints only "low"
    }
    std::cout << "---\n";

    std::cout << "low:  " << to_string(flag::low) << std::endl;  // prints only "low:  low"
    std::cout << "high: " << to_string(flag::high) << std::endl; // ⚠ `to_string(flag::high)` returns ""!
}
```
I've tried `main_with_range.cc` with multiple versions of `magic_enum` and multiple compilers:

| magic_enum Version | MSVC 2022 | Clang/LLVM 11 | GCC 9.4 |
|---------|---------|---------|---------|
| 0.7.3 | Works ✔| Works ✔| Works ✔|
| 0.8.0 | Works ✔| Works ✔| Works ✔|
| 0.8.1 | Works ✔| Works ✔| Works ✔|
| 0.8.2 | Works ✔| **Breaks** ❌| **Breaks** ❌|
| 0.8.2 (with `MAGIC_ENUM_ENABLE_HASH`)\* | Works ✔| Works ✔ | Works ✔|

\* enabled via `cmake -DENABLE_FIX=ON`

## Conclusion
It seems like the behavior of `magic_enum::enum_name` changes if `magic_enum::enum_values` has been used anywhere else. Given that it worked in several previous versions, this seems like a defect within 0.8.2., but I'm not entirely sure.

Note that `main_with_range.cc` works fine if one includes `enum.cc` instead of `enum.h`, but I can't count on all downstream users and developers to redefine the `magic_enum::customize::enum_range` specialization.

**Comment by bkaestner** [comment]
Sorry for the comment/ping spam, didn't realise that the issue number would also come up here!

Anyway, I have the test case from the [initial post in a branch on a fork,](https://github.com/bkaestner/magic_enum/tree/issue-231-replication). It needs a little bit of cleanup, but I can prepare a pull request if it helps. What's interesting is that it's not enough to have a unused function, the call to `enum_values` must not be optimized out (see [run #5](https://github.com/bkaestner/magic_enum/actions/runs/3831466370)).

Also, it seems like this issue only occurs in `Debug`, not in `Release`:

| Workflow | Debug | Release |
|--|--|--|
|windows| Works ✔ | Works ✔ |
|macos| Breaks ❌ | Works ✔ |
|ubuntu| Breaks ❌ | Works ✔ |

**Comment by bkaestner** [comment]
Follow-up to yesterday's investigation: according to `git bisect`, this behavior was introduced in 8bd403f888955fc9133b4bc79ffc3740c4f44034. Hope that helps :)

**Comment by Neargye** [comment]
Hi, unfortunately, I couldn't find a solution to have the `to_string` use custom::range inside cpp. As you can see, it depends on the build parameters, and much more, and I cannot guarantee that it will work like in your example inside the library.

For this to always work, I advise you to use specialization inside the hpp file - more about why this is so here https://isocpp.org/wiki/faq/templates#templates-defn-vs-decl.

**Comment by Neargye** [comment]
A more convenient solution might be

1. Create `my_magic_enum_cfg.hpp` with all specialization `magic_enum::customize::enum_range`
2. Add option `-DMAGIC_ENUM_CONFIG_FILE=my_magic_enum_cfg.hpp`

**Comment by Neargye** [comment]
The problem is that
For example, a `to_string` from cpp might work as you expect, but when you will call `magic_enum::enum_count<flag>()` it's will return 1.

You can check your example like this
```cpp
#include <iostream>

#include "enum.h"
#include "magic_enum.hpp"

int main() {
    std::cout << magic_enum::customize::enum_range<flag>::min << std::endl;
    std::cout << magic_enum::customize::enum_range<flag>::max << std::endl;
    std::cout << to_string(flag::low) << std::endl;  // prints "low", as expected
    std::cout << to_string(flag::high) << std::endl; // prints "high", as expected
}
```

**Comment by bkaestner** [comment]
> For this to always work, I advise you to use specialization inside the hpp file - more about why this is so here https://isocpp.org/wiki/faq/templates#templates-defn-vs-decl.

Yeah, we explicitly tried to avoid the specialization inside the `.hpp` in order to keep the `<magic_enum.hpp>` dependency within our object files and not leak it into the headers (i.e. `target_link_libraries(PRIVATE ...)` vs `target_link_libraries(PUBLIC ...)`).

> Hi, unfortunately, I couldn't find a solution to have the `to_string` use `custom::range` inside cpp.

Thanks for trying, very much appreciated. It's a very edge case (trying to hide the customization in implementation), so we'll just bite and add it within the header, that will work fine without relying on future compiler updates.

**Comment by Neargye** [comment]
You can try another option, make all the necessary functions similar to `to_string` and do not use functions directly from the library

**Comment by ZXShady** [comment]
This is a classic odr voilation all libraries suffer from it so yea the solution is to stick it with the enum in the header
