### ISSUE TITLE
Feature proposal: contains function for flags

### ISSUE THREAD

**Issue by jonpetri** [Neargye/magic_enum#234]
### The proposal is a nutshell
Add a new bitwise operator that allows to do: `flags <contains> flag`.

### Details
When working with flags we usually test a lot whether a given flag is in a flag field.
For instance:
```cpp
enum class AnimalFlags
{
    None = 0,
    HasClaws = 1 << 1,
    CanFly = 1 << 2,
    EatsFish = 1 << 3,
    Endangered = 1 << 4
};

AnimalFlags catFlags = AnimalFlags::HasClaws | AnimalFlags::EatsFish;

if (AnimalFlags::EatsFish == (catFlags & AnimalFlags::EatsFish)) // <- test if a given flag is in a flag field.
{
    // if catFlags contains EatsFish ...
}
```

It would be very bandy and much readable to write something like:
```cpp
if (catFlags <contains> AnimalFlags::EatsFish)
{
```
To achieve that, this technique is very interesting:
https://github.com/klmr/named-operator
It allows to create named operators of this kind.

**So here is my proposal:** add a new bitwise operator that allows to do: `flags <contains> flag`.
It would be implemented inspired by the "named operator" technique, but without creating a dependency to that repo.

### Alternative
We can also add a classic function that provides the same service, something like:
`bool anyFlagMatches(E flags1, E flags2)`, but this is less readable.

**Comment by Neargye** [comment]
It seems to me that creating a "named operator" overloads the interface of the library a bit.

Or we can create a separate header containing operators and functions for flags, `magic_enum_flags.hpp` for example.

**Comment by jonpetri** [comment]
I agree that the "named operator" will add an uncommon interface, and therefore an overload.

The classic way to write a "contains" function would be `bool contains(E flags, E flag)`
hmm... it is not that bad. The drawback is that the function is prone to being called with swapped / badly ordered arguments. But in the end the arguments can be swapped with the "named operator" too.

I'll prepare a PR with a  implementation proposition of `bool contains(E flags, E flag)` in a new file: `magic_enum_flags.hpp`

**Comment by schaumb** [comment]
I think the clearest solution would look like this:
https://godbolt.org/z/boj44hKPz

```
using magic_enum::containers::set;

if (set(catFlags).contains(AnimalFlags::EatsFish)) ...
```


There are multiple issues that must resolve to work this:

So the first problem is:

- `magic_enum::detail::is_flags_v<AnimalFlags>` is false. Because no enum with value `1`. Is this intended @Neargye?
- There are no constructor deduction guides for the container classes, so the `set<AnimalFlag>(....)` needs to be used as a replacement
- But that's not working because of a bug [here](https://github.com/Neargye/magic_enum/blob/master/include/magic_enum_containers.hpp#L990), this must be `a[v] = true`.

**Comment by jonpetri** [comment]
@schaumb 
Here is how you can implement this. I do not think there are any bug, perhaps just a lack of documentation :relaxed:
But the comments below explain the misunderstandings:
```cpp
#include <magic_enum_containers.hpp>
#include <iostream>

enum class AnimalFlags
{
    None = 0,
    HasClaws = 1 << 0,
    CanFly = 1 << 1,
    EatsFish = 1 << 2,
    Endangered = 1 << 3
};

// Add the property is_flags to AnimalFlags specialization to be allowed to
// build a set out of it
template <>
struct magic_enum::customize::enum_range<AnimalFlags>
{
    static constexpr bool is_flags = true;
};

template<typename E>
using magic_enum_set = magic_enum::containers::set<E>;

int main() {
    static_assert(magic_enum::detail::is_flags_v<AnimalFlags>);

    // The set is built from a initializer list of individual flags
    magic_enum_set<AnimalFlags> catFlagsSet = magic_enum_set<AnimalFlags>({AnimalFlags::HasClaws, AnimalFlags::EatsFish});

    if (catFlagsSet.contains(AnimalFlags::EatsFish))
    {
        std::cout << "The cat can eat fish" << std::endl;
    }
    else
    {
        std::cerr << "ERROR: The cat cannot eat fish" << std::endl;
    }

    if (!catFlagsSet.contains(AnimalFlags::CanFly))
    {
        std::cout << "The cat can't fly" << std::endl;
    }
    else
    {
        std::cerr << "ERROR: The cat can fly" << std::endl;
    }
}
```

But I still think that magic_enums should propose a simple function to test the `contains`, directly on an an enum value, without the overhead of a set container.

I'm coming with a PR soon, sorry for the delay,  I'm a bit busy those times.

**Comment by schaumb** [comment]
I co-created the containers package.

```
magic_enum_set<AnimalFlags> catFlagsSet = magic_enum_set<AnimalFlags>({AnimalFlags::HasClaws, AnimalFlags::EatsFish});
```
This definition can be simplified (no need explicit template argument):
```
auto catFlagsSet = magic_enum_set{AnimalFlags::HasClaws, AnimalFlags::EatsFish};
```

I fixed the 'flag' version too (my example) at https://github.com/Neargye/magic_enum/pull/271, where no needed to list all enum value in constructor.
```
auto catFlags = AnimalFlags::HasClaws | AnimalFlags::EatsFish;
auto catFlagsSet = magic_enum_set(catFlags);
```
