### ISSUE TITLE
magic_enum::enum_name doesn't return the right string if a prefix is a symbol

### ISSUE THREAD

**Issue by l16i** [Neargye/magic_enum#241]
Hello,

I'm using a API rest and I've a enum class that match some of its fields. Some of them have a `$` prefix.

My enum look like this:
```c++
enum class MyEnum { 
$fieldOne,
$field_two
};
```

When I use the `magic_enum::enum_name` function the string is wrong and the prefix `$` is not here anymore. I get the following results:

```c++
const auto fieldOne = magic_enum::enum_name< MyEnum>(MyEnum::$fieldOne);
// "fieldOne" instead of "$fieldOne"

const auto fieldTwo = magic_enum::enum_name< MyEnum>(MyEnum::$fieldTwo);
// "field_two" instead of "$field_two"
```

Is it expected? Or did I do something wrong?

Thanks

**Comment by Neargye** [comment]
Please retest on new master

**Comment by l16i** [comment]
@Neargye Sorry for the late reply. I was busy with another project.
I just tested it, and it works like a charm! Thanks for the update!
