### ISSUE TITLE
The `magic_enumConfigVersion.cmake` file is being generated in a different folder than `magic_enumConfig.cmake`

### ISSUE THREAD

**Issue by joseviccruz** [Neargye/magic_enum#242]
... Consequently the variable `magic_enum_VERSION` is empty.

On Ubuntu 22.10:

- Installing:
```bash
mkdir build
cd build
cmake .. -DCMAKE_INSTALL_PREFIX="/opt/magic_enum" -DMAGIC_ENUM_OPT_INSTALL=TRUE -DMAGIC_ENUM_OPT_BUILD_TESTS=FALSE
make -j$(nproc)
make install
```

- Generated files visualization:
```bash
magic_enum/
├── include
│   ├── magic_enum_containers.hpp
│   ├── magic_enum_format.hpp
│   ├── magic_enum_fuse.hpp
│   ├── magic_enum.hpp
│   └── magic_enum_switch.hpp
├── lib
│   ├── cmake
│   │   ├── magic_enum
│   │   │   └── magic_enumConfig.cmake
│   │   └── magic_enumConfigVersion.cmake # seems to be wrong
│   └── pkgconfig
│       └── magic_enum.pc
└── share
    └── magic_enum
        └── package.xml
```

- Inside another CMake project:
```CMake
find_package(magic_enum CONFIG REQUIRED HINTS "/opt/magic_enum")

message(STATUS "Using magic_enum: ${magic_enum_VERSION}") # empty
```

I moved the file `magic_enumConfigVersion.cmake` manually after installation and it seemed to work:

```bash
magic_enum/
├── include
│   ├── magic_enum_containers.hpp
│   ├── magic_enum_format.hpp
│   ├── magic_enum_fuse.hpp
│   ├── magic_enum.hpp
│   └── magic_enum_switch.hpp
├── lib
│   ├── cmake
│   │   └── magic_enum
│   │       ├── magic_enumConfig.cmake
│   │       └── magic_enumConfigVersion.cmake
│   └── pkgconfig
│       └── magic_enum.pc
└── share
    └── magic_enum
        └── package.xml
```

**Comment by Neargye** [comment]
@KOLANICH do you have a chance to look at this problem?

**Comment by KOLANICH** [comment]
I usually set CMAKE_PREFIX into `/usr` before generating packages, not `/opt`. I'm not sure if CMake and pkgconfig search in `/opt`

**Comment by joseviccruz** [comment]
@KOLANICH The same problem occurs installing in `/usr`: the configuration file is found but the version one is not.

**Comment by KOLANICH** [comment]
Thanks for reporting this issue, I should investigate it. 

It seems tuat I have forgotten to replace

`DESTINATION "${CMAKE_INSTALL_LIBDIR_ARCHIND}/cmake/${CMAKE_EXPORT_NAME}"`

(`CMAKE_EXPORT_NAME` is the internal variable in my `Boilerplate.cmake` script)

with

`DESTINATION "${CMAKE_INSTALL_LIBDIR_ARCHIND}/cmake/${PROJECT_NAME}"`

Could you try #243?

**Comment by joseviccruz** [comment]
Nice!
It worked here ✅
