### ISSUE TITLE
magic_enum::customize::enum_name only works in one file

### ISSUE THREAD

**Issue by lifeforce-dev** [Neargye/magic_enum#245]
It appears that if I want a custom enum name, I have to define its specialization in the file where the custom name will be used? i.e I can't have a types.h which defines enums and a types.cpp which specializes their names, and then log their names throughout the program?

If this is the case then its a pretty significant limitation for anything more complex than `int main() { example_code }` but I hope I'm just doing something wrong.

**Comment by Neargye** [comment]
Looks similar to https://github.com/Neargye/magic_enum/issues/231

**Comment by lifeforce-dev** [comment]
Ah nice, yup looks like it!

**Comment by Neargye** [comment]
I advise you to use specialization inside the hpp file - more about why this is so here https://isocpp.org/wiki/faq/templates#templates-defn-vs-decl.

A more convenient solution might be

1. Create my_magic_enum_cfg.hpp with all specialization magic_enum::customize::enum_range
2. Add option -DMAGIC_ENUM_CONFIG_FILE=my_magic_enum_cfg.hpp
