### ISSUE TITLE
Enum type name?

### ISSUE THREAD

**Issue by no-more-secrets** [Neargye/magic_enum#25]
Is there a way to get the name of an enum type?  E.g.:

```
enum class e_color { red, blue };
using my_enum = e_color;
constexpr std::string_view name = magic_enum::enum_type_name<my_enum>();
```

then `name` would be "e_color".

**Comment by Neargye** [comment]
Hi @dpacbach,

https://github.com/Neargye/magic_enum/blob/52d7323bcab2be4b32191ef587825736c5eef879/include/magic_enum.hpp#L344

```cpp
enum class e_color { red, blue };
using my_enum = e_color;
constexpr std::string_view name = magic_enum::enum_traits<my_enum>::type_name;
```

**Comment by Neargye** [comment]
To get the name of any type, see https://github.com/Neargye/nameof.

**Comment by no-more-secrets** [comment]
Thanks for the answer and the pointer to `nameof`.  I think the `magic_enum::enum_traits` is what I was looking for.

**Comment by Neargye** [comment]
Now added new API `magic_enum::enum_type_name`
```cpp
enum class color { red, blue };
using my_enum = e_color;
constexpr std::string_view name1 = magic_enum::enum_type_name<my_enum>(); // color 
color r = color::red;
constexpr std::string_view name2 = magic_enum::enum_type_name<decltype(r)>(); // color 
```

**Comment by no-more-secrets** [comment]
Thank you
