### ISSUE TITLE
adding magic_enum to conda-forge

### ISSUE THREAD

**Issue by versatran01** [Neargye/magic_enum#250]
Hi, I created an initial PR to add magic_enum to conda-forge
https://github.com/conda-forge/staged-recipes/pull/22341
@Neargye would you like to be a maintainer of this conda recipe?

P.S. I'm unfamiliar with how to do this for windows correctly, if anyone knows please let me know.

**Comment by Neargye** [comment]
I have not worked and do not know how to work with conda.  That's why I'm not the best person to maintain it.

**Comment by versatran01** [comment]
Close since it has been added to conda
