### ISSUE TITLE
Is it possible to release the current master with enum containers?

### ISSUE THREAD

**Issue by selevit** [Neargye/magic_enum#256]
Hello, and thanks for the great library!

I noticed that it has a great feature with enum containers that lets you avoid manual casting when working with arrays, indexed by enums, bitsets and so on.

But unfortunately it's not yet released yet. Since I use the version from conan, this functionality is unavailable now.

Have any plans of releasing this in the nearest future?

**Comment by Neargye** [comment]
Unfortunately the new version is a little delayed, I need to fix some problems that entail an improvement in internal stuff, I will try to release the version as soon as possible

**Comment by Neargye** [comment]
Released
