### ISSUE TITLE
E0028 expression must have a constant value

### ISSUE THREAD

**Issue by Xis-Ytneves** [Neargye/magic_enum#26]
/ E2719 integer constant must be greater than or equal to zero
 on this line ...
inline constexpr auto type_name_v = n<E>();

any ideas what these errors could be? it compiles and works ... just not sure why intellisense is unhappy

**Comment by Neargye** [comment]
Hi @Xis-Ytneves, it seems code analysis is too complex for IntelliSense.

**Comment by Neargye** [comment]
I would just suggest ignoring IntelliSense errors for the file magic_enum.hpp.

**Comment by Xis-Ytneves** [comment]
thanks, will do!
