### ISSUE TITLE
When is_flags is set the zero enum entry is not printed

### ISSUE THREAD

**Issue by habakuk007** [Neargye/magic_enum#263]
When `is_flags` is not set then the `magic_enum::ostream_operators` prints the name for the 0 value of the enum (`enum class`).

When `is_flags`  is set then `0` is printed instead of the name.

Tested with version 0.8.2

Without `is_flags`:
![grafik](https://github.com/Neargye/magic_enum/assets/2253878/fbf59a1b-f3a9-44fa-a471-5cb33e9f49e0)

With `is_flags`:
![grafik](https://github.com/Neargye/magic_enum/assets/2253878/c68f04e6-4bf2-4079-b5e3-e524063e8d11)

**Comment by Neargye** [comment]
Hi,

For enum-flags add is_flags to specialization enum_range for necessary enum type. Specialization of enum_range must be injected in namespace magic_enum::customize.
```cpp
enum class Directions { Up = 1 << 1, Down = 1 << 2, Right = 1 << 3, Left = 1 << 4 };
template <>
struct magic_enum::customize::enum_range<Directions> {
  static constexpr bool is_flags = true;
};
```
If not add `is_flags` then the default range for magic_enum is -128 to 128 see https://github.com/Neargye/magic_enum/blob/master/doc/limitations.md. Also you can force control "flags-behavior", for example
```cpp
enum { X = 1, Y = 2, Z = X | Y};
magic_enum::enum<as_common<>>(E::Z) -> 'Z'
magic_enum::enum<as_flags<>>(E::Z) -> '' // null-string
```

Zero is not flag, aslo are "bits or" `Z = X | Y` is not flag. Unfortunately, these libs restrictions.

**Comment by Neargye** [comment]
If you need to output zero, I would advise you to do something like this
```cpp
auto myenum_name(E v) {
if (v == 0)
  return magic_enum::enum_name<E, 0>();
return magic_enum::enum_name<E>(v);
}
```

**Comment by habakuk007** [comment]
> If you need to output zero, I would advise you to do something like this

Thanks!

This worked for me:

```
void write_warning_string(std::ofstream& fs, vdp::algorithm::Algorithm_warnings const warnings)
{
	if (static_cast<int>(warnings) == 0)
		fs << magic_enum::enum_name<vdp::algorithm::Algorithm_warnings::no_warning>();
	else
		fs << warnings;
}
```
