### ISSUE TITLE
Beginner question: Assign enum_name to std::string

### ISSUE THREAD

**Issue by manuelbauer1603** [Neargye/magic_enum#264]
Beginner here.
Why is it not possible to do this:
`std::string sVar = magic_enum::enum_name(enumObj);`

What would be the right way to assign the enum_name to a std::string?

**Comment by Neargye** [comment]
```
auto sVar = std::string{magic_enum::enum_name(enumObj)};
auto sVar = static_cast<std::string>(magic_enum::enum_name(enumObj));
```

magic_enum::enum_name return [string_view](https://en.cppreference.com/w/cpp/string/basic_string_view)
