### ISSUE TITLE
Update containers to new API

### ISSUE THREAD

**Issue by Neargye** [Neargye/magic_enum#266]

**Comment by Neargye** [comment]
Hi @schaumb

Could you review the containers update? 
Auto-detect `is_flags` was disabled due to unstable result and also a long compilation time. Now need to explicitly set that the enum flag is, or add a define `MAGIC_ENUM_AUTO_IS_FLAGS`.

Do we still have a bug? (from comment https://github.com/Neargye/magic_enum/issues/234#issuecomment-1468134598)

**Comment by schaumb** [comment]
Hi!

It's OK, I created a new PR https://github.com/Neargye/magic_enum/pull/271 for it.

**Comment by Neargye** [comment]
Thank you very much!
