### ISSUE TITLE
Include some documentation on how it works

### ISSUE THREAD

**Issue by jrmuizel** [Neargye/magic_enum#27]
It would be nice to read an overview of the technique used here. I tried reading through it but got a lost around `n()`

**Comment by Neargye** [comment]
Hi @jrmuizel,
It's working by magic!

But seriously:
* `n()` use a compiler-specific hack (based on __PRETTY_FUNCTION__ / __FUNCSIG__) to get enum name in compile-time.
* We go through the given interval `enum_range`, and find all the enumerations with a name and same in `enum_values`.
* Then, using the indexes stored in the array, we get the names and etc.
* Read more about [limitations](https://github.com/Neargye/magic_enum/blob/master/doc/limitations.md)
