### ISSUE TITLE
Latest master branch prepends enum's namespace

### ISSUE THREAD

**Issue by rpatters1** [Neargye/magic_enum#274]
Suppose I have

```c++
class foo {
public:
   enum Nums {
      ZERO,
      ONE,
      TWO
   };
};
```

In versions of `magic_enum` prior to the latest push (e.g., commit `5367f51`), `enum_names<foo::Nums>` would return:

```
"ZERO"
"ONE"
"TWO"
```

It appears that now it returns:

```
"foo::ZERO"
"foo::ONE"
"foo::TWO"
```

This breaks my code. (I am using XCode 14.2 on macOS 12.6.5.) If the new behavior is by design, it would be very helpful to have an option to disable it.

**Comment by Neargye** [comment]
Fix in master

**Comment by Neargye** [comment]
Please retest on master branch, and I will prepare hotfiix release.

**Comment by rpatters1** [comment]
Hello. I will certainly test this when I get back to my dev machine on Thursday or Friday.

**Comment by Neargye** [comment]
Please reopen if still present.

**Comment by rpatters1** [comment]
It appears to work. If I run into any further issues, I'll let you know.

**Comment by Neargye** [comment]
Thanks!

**Comment by pateldeev** [comment]
I am still seeing issues with enums in an anonymous namespace

https://godbolt.org/z/jTnWE7c5x

**Comment by Neargye** [comment]
@pateldeev please create new issues

**Comment by Neargye** [comment]
@pateldeev  It seems that godbolt does not pull fresh master, becausen locally works  for me

https://godbolt.org/z/brWrcfdKq

**Comment by Neargye** [comment]
Yes, on godbolt  trunck = 0.9.0

**Comment by Neargye** [comment]
In any case, I added new tests to check anonymous namespaces. Thanks

**Comment by Neargye** [comment]
And test found that problem with enum name in an anonymous namespace on Clang https://github.com/Neargye/magic_enum/issues/276

**Comment by pateldeev** [comment]
Ah yes. I double checked, and I originally noticed the empty string for clang. Thanks for fixing!
