### ISSUE TITLE
Compilation fails with Visual Studio 2017

### ISSUE THREAD

**Issue by cwe-skov-dk** [Neargye/magic_enum#278]
I am trying to build magic_enum v0.9.1 with Visual Studio 2017, but compilation fails. See the attached log of my build for reference.

The build fails with similar errors for magic_enum master.

[build.log](https://github.com/Neargye/magic_enum/files/11650490/build.log)

**Comment by Neargye** [comment]
@cwe-skov-dk  please retest on new master

**Comment by cwe-skov-dk** [comment]
Works like a charm, thanks for the quick fix!
