### ISSUE TITLE
Previous/next value helpers

### ISSUE THREAD

**Issue by turol** [Neargye/magic_enum#280]
There should be a way to get previous/next value in the enum, something like this:

https://github.com/turol/smaaDemo/blob/31ba838df401122afb62ebbf4c6b49c93108b011/demo/smaaDemo.cpp#L252

https://github.com/turol/smaaDemo/blob/31ba838df401122afb62ebbf4c6b49c93108b011/demo/smaaDemo.cpp#L2595

**Comment by Neargye** [comment]
For example
```cpp
enum class SMAAEdgeMethod : uint8_t {
	  Color
	, Luma
	, Depth
};
```
`nextValue(SMAAEdgeMethod::Depth)` - occur error or return SMAAEdgeMethod::Color ?


https://en.cppreference.com/w/cpp/iterator/next  for example throws an error (I would probably prefer to return optional<E>)

**Comment by turol** [comment]
In my case I cycle again to the beginning. You could of course add both variants.

**Comment by turol** [comment]
On further thinking there should probably be the following variants:

1. `cycle_prev/cycle_next` does what I currently do.
2. `prev/next` does what you suggested, throws exception
3. `prev_opt/next_opt` returns a `std::optional`

This should cover every use case.

**Comment by Neargye** [comment]
Add 2 variants in master:
* cycle_prev/cycle_next does what I currently do.
* prev/next returns a std::optional

https://github.com/Neargye/magic_enum/blob/master/include/magic_enum_utility.hpp
