### ISSUE TITLE
enum_type_name includes the whole namespace

### ISSUE THREAD

**Issue by Bernhard-L** [Neargye/magic_enum#281]
the Version 0.9.2 breaks our code (like https://github.com/Neargye/magic_enum/issues/274)
but not when using enum_name but when using enum_type_name

(tested with MSVC 19 - Windows)

runs with 0.8.2
TEST(scoped_enum_test, enum_type_name_Test)
{
	enum class test_enum
	{
		first,
		second,
		third
	};

	EXPECT_EQ(std::string(magic_enum::enum_type_name<test_enum>()), "test_enum");
}

breaks (at least with 0.9.2 - skipped the versions inbetween because of https://github.com/Neargye/magic_enum/issues/274)

result of test
Expected equality of these values:
  std::string(magic_enum::enum_type_name<test_enum>())
Which is: "scoped_enum_test_enum_type_name_Test_Test::TestBody::test_enum"
  "test_enum"

**Comment by Neargye** [comment]
In the master, this should be fixed. I will prepare a new version soon.

I'm sorry, these problems happen because not all options were covered in the tests.

**Comment by Neargye** [comment]
Fix released in v0.9.3

**Comment by Bernhard-L** [comment]
thanks a lot - and keep on with the great work!
