### ISSUE TITLE
Suggest Adoption of Scorecard GitHub Action

### ISSUE THREAD

**Issue by diogoteles08** [Neargye/magic_enum#283]
Hey, I'm Diogo and I've raised the issues #247 and #269 contributing with some security enhancements. I'll happily continue contributing with such improvements (it's literally my job, see [my profile](https://github.com/diogoteles08/diogoteles08/blob/main/README.md#about-gosst-ghost)), but this time I come to suggest the tool that I used myself to find those security issues.

I'd like to suggest that the project add the [OpenSSF Scorecard Action](https://github.com/ossf/scorecard-action). The OpenSSF Scorecard uses GitHub's public API to gather public informations about your project and runs a sort of "meta-analysis" of the project's security posture. The Action then populates the project's [Security Panel](https://github.com/Neargye/magic_enum/security) with possible improvements to its security posture. It's specially helpful to ensure you won't regress on the security measures you have already adopted. Additionally, the tool integrates with the [OSV Scanner](https://security.googleblog.com/2022/12/announcing-osv-scanner-vulnerability.html), which evaluates a project's transitive dependencies looking for known vulnerabilities.

When working on the Security enhancements pointed by Scorecard, you're also able to apply for the [OpenSSF's Secure Open Source Rewards](http://sos.dev/) program, which financially rewards developers for improving the security of important open source projects

This tool is developed by the OpenSSF [in partnership with GitHub](https://github.blog/2022-01-19-reducing-security-risk-oss-actions-opensff-scorecards-v4/) and it's already been adopted by 1800+ projects, including [Tensorflow](https://github.com/tensorflow/tensorflow), [PyTorch](https://github.com/pytorch/pytorch), [Angular](https://github.com/angular/angular), and [Flutter](https://github.com/flutter/flutter).

If you're interested, let me know and I'll send a PR!

**Comment by diogoteles08** [comment]
Hey! This issue/PR has been idle for quite some time. Do you plan on considering this suggestion? If not, I'll probably wait up to 2 more months and close the issue.

Thanks!

**Comment by Neargye** [comment]
Hi @diogoteles08, please create pr, I will take a look. Thanks!
