### ISSUE TITLE
Compilation issues when using the magic_enum-library in a CLI/C++-project

### ISSUE THREAD

**Issue by Baardi** [Neargye/magic_enum#284]
Hey.

We've been using this library for a while, and it does it's job well. 
But we've ran into some issues when upgrading from v0.8 to v0.9.3.

I get the following errors:
![Skjermbilde 2023-06-28 165703-kopi](https://github.com/Neargye/magic_enum/assets/19634818/967c63b2-daa5-4b9c-88e1-c98adaf328c2)

I get similar errors using enum_name. Note that the input parameter is a regular std::string. A simple reproduction case would be something like this:

![bilde](https://github.com/Neargye/magic_enum/assets/19634818/7e1c6119-a709-4578-9681-ae645357f056)

It seems that the only real requirement to reproduce this is to try to compile it with a CLR-switch, as it compiles fine from a pure c++ project. I can link you an example project reproducing this, if necessary
Is C++/CLI beyond the scope of what this library wants to support, or do you welcome changes that allows for it?

I'm asking considering it worked in v0.8, and because it is a useful tool for converting between C# and C++ enums (going by string instead of underlying value)

**Comment by Neargye** [comment]
Hi,
it looks like some nuances of working `__FUNCSIG__` on CLI/C++.  I've never used it myself CLR, but if you could please give me an example where I can check.

**Comment by Neargye** [comment]
Could you test the latest master?

**Comment by Baardi** [comment]
Yes that worked. I guess you don't need the reproduction case anymore?

**Comment by Neargye** [comment]
Yes, an example is not needed, thanks.
I downloaded CLR locally, to be honest, I did not fully understand the cause of the error, but this solution seems to work ok.

**Comment by BartmanAbyss** [comment]
Thanks for the fix. Just noticed the breakage last week.
