### ISSUE TITLE
Implicit conversion from containers::bitset to bool

### ISSUE THREAD

**Issue by labankallgren** [Neargye/magic_enum#285]
Is there anyway to implicitly check the boolean value of a containers::bitset, or must one use `containers::bitset::any()` method for that?
What I'd like to do:
```c++
containers::bitset<T> A{};
containers::bitset<T> B{};
if(A & B) {
  // ...
}
```

**Comment by Neargye** [comment]
I looked at the problem in detail, the std::bitset does not have such bool operator, it is better to really use any().
