### ISSUE TITLE
Support enum with unsorted integers

### ISSUE THREAD

**Issue by rex0707** [Neargye/magic_enum#287]
Hi,

If enum integers are not sorted by dafult, I will get wrong enum by giving index.
I want to check is sorted array necessary.

Thanks.

Ex: 
enum class Color { RED = -10, BLUE = -20, GREEN = 10};
int main()
{
  std::size_t index = 1;
  auto color = magic_enum::enum_value<Color>(index);
  std::cout << (color == Color::BLUE) << std::endl; // Will get false here

  return 0;
}

**Comment by Neargye** [comment]
Hi,
Unfortunately, due to limitations, the array of values cannot be unsorted.
