### ISSUE TITLE
Publish to bazel central registry

### ISSUE THREAD

**Issue by zaucy** [Neargye/magic_enum#288]
I started a draft to submit magic_enum to the BCR: https://github.com/bazelbuild/bazel-central-registry/pull/811

The current problem with it is they require an archive be released instead of relying on the generated one. Reasoning for that is here: https://blog.bazel.build/2023/02/15/github-archive-checksum.html. Could an archive be added to the release assets?

Also to publish automatically on release the [Publish to BCR](https://github.com/bazel-contrib/publish-to-bcr) GitHub app could be used.

**Comment by Neargye** [comment]
Hi,
will take a look and try add archive
