### ISSUE TITLE
Incorrect behaviour with clang on enums defined inside template classes

### ISSUE THREAD

**Issue by johnilacqua** [Neargye/magic_enum#296]
When used on an enum defined inside a templated class, `magic_enum::enum_count<MyEnum>()` returns 0 instead of the correct value when compiled with clang.

https://godbolt.org/z/vqasE9M13

```
#include <magic_enum.hpp>

template <typename SomeType>
class TestClass
{
    enum class MyEnum
    {
        VALUE
    };

    static_assert(magic_enum::enum_count<MyEnum>() == 1);
};

TestClass<int> t;
```

**Comment by johnilacqua** [comment]
To add, this only happens with an `enum class`, not if it's just an `enum`.

**Comment by Neargye** [comment]
Hi,
Unfortunately, this is a problem with the Сlang compiler, perhaps an optimization bug, we don’t know how to get around it
See https://github.com/Neargye/magic_enum/issues/164, https://github.com/Neargye/magic_enum/issues/65
