### ISSUE TITLE
ranges formatting fails with fmt

### ISSUE THREAD

**Issue by JeffGarland** [Neargye/magic_enum#298]
There's something about the enum formatter code that isn't compatible with the fmt ranges formatting facilities. That is, a single value will format fine, but when using it in range formatting it fails.  Note that if I hand write the standard fmt boiler plate using magic enum then there's no issue -- so I'm assuming this is a problem in magic_enum and not fmt. 

```cpp
//...other stuff....
enum class whatev2 {foo, bar, baz};
std::array<whatev2, 2> wev2_array = { whatev2::baz, whatev2::bar };

int main () 
{

  whatev we = whatev::foo;
  fmt::print("{}\n", we);
  fmt::print("{}\n", wev_array); //hand written format using magic_enum - ok
  ///opt/compiler-explorer/libs/fmt/trunk/include/fmt/ranges.h:485:31: error: passing 'fmt::v10::detail::range_formatter_type<char, whatev2>' {aka 'const fmt::v10::formatter<whatev2, char, void>'} as 'this' argument discards qualifiers [-fpermissive]
  //485 |       out = underlying_.format(mapper.map(*it), ctx);
  //fmt::print("{}\n", wev2_array);
}
```
All details here:

https://godbolt.org/z/W7aK65334

**Comment by Neargye** [comment]
Hi, thanks for issues
Add fix in master, now look ok
https://godbolt.org/z/xc1asf6dW

**Comment by Neargye** [comment]
https://godbolt.org/z/xc1asf6dW

**Comment by edelmanjm** [comment]
This is still failing for me when trying to format `std::vector<std::byte>`.

- [Here's the failing example](https://godbolt.org/z/qKaYbzbKx): with both `#include <fmt/ranges.h>` and `#include <magic_enum/magic_enum_format.hpp>`, I get a compiler error.
- [Removing  `#include <fmt/ranges.h>` allows it to compile](https://godbolt.org/z/TTW4dc7aP)
- [Removing  `#include <magic_enum/magic_enum_format.hpp>` also allows it to compile](https://godbolt.org/z/7rjYvPb7n)

**Comment by Neargye** [comment]
> This is still failing for me when trying to format `std::vector<std::byte>`.
> 
> 
> 
> - [Here's the failing example](https://godbolt.org/z/qKaYbzbKx): with both `#include <fmt/ranges.h>` and `#include <magic_enum/magic_enum_format.hpp>`, I get a compiler error.
> 
> - [Removing  `#include <fmt/ranges.h>` allows it to compile](https://godbolt.org/z/TTW4dc7aP)
> 
> - [Removing  `#include <magic_enum/magic_enum_format.hpp>` also allows it to compile](https://godbolt.org/z/7rjYvPb7n)

Please open new issues, I will try to investigate
