### ISSUE TITLE
Argument-dependent lookup results in `invoke_r` ambiguity

### ISSUE THREAD

**Issue by ZeroMemes** [Neargye/magic_enum#299]
When using MSVC with `/std:c++latest`, `magic_enum::detail::constexpr_switch_impl`'s call to `magic_enum::detail::invoke_r` is deemed ambiguous with `std::invoke_r` due to argument-dependent lookup via `std::forward`.

This error doesn't happen on Clang or GCC when using libc++, but does happen on Clang when using the Microsoft STL.

https://godbolt.org/z/Ksscz6azE

**Comment by Neargye** [comment]
fix in master
