### ISSUE TITLE
Add conan support

### ISSUE THREAD

**Issue by gocarlos** [Neargye/magic_enum#3]
It would be great to use this lib using cmake and conan

**Comment by Neargye** [comment]
Cmake install already added.

**Comment by Neargye** [comment]
Hi @gocarlos, I add the latest release to Conan. Could you please check all ok with Conan?

**Comment by rdeterre** [comment]
Hello @Neargye,

The Conan package in [your bintray repository](https://bintray.com/neargye/conan-packages) works great, thanks. Would you be willing to submit it for inclusion in Conan-Center? This would make the package reachable for anyone that uses Conan, without having to add your personal repository.

https://docs.conan.io/en/latest/uploading_packages/bintray/conan_center_guide.html

Thanks.

**Comment by Neargye** [comment]
Hi @rdeterre, Thanks for the test.
I planed release 0.6.1, then push nameof to conan-center.

**Comment by gocarlos** [comment]
even better now: https://blog.conan.io/2019/09/04/A-new-binary-building-service-for-Conan-center-packages.html
