### ISSUE TITLE
A dll is compileable but not available with Visual Studio 2022.

### ISSUE THREAD

**Issue by DWin233** [Neargye/magic_enum#302]
I used the following two enum classes, which were converted to strings normally in independent testing. But in my DLL, they cannot be converted while other enum classes with few items were converted to strings normally. enum_name would return a empty string and enum_cast would return a nullopt.
The above errors all appear in Visual Studio 2022 debug mode and disappear in release mode. Now I only know that the problem will occur under the above conditions, and I don't know how to reproduce it.
The version 0.9.3 is used.

```
enum class TallyType : uint32_t
  {
      None = 0,
      AbsorptanceTotal = 1,
      AbsorptanceOfDepth = 2,
      AbsorptanceOfRho = 3,
      AbsorptanceOfRhoDepth = 4,
      FluenceOfDepth = 5,
      FluenceOfRhoDepth = 6,
      ReflectanceDiffuse = 7,
      ReflectanceOfAngle = 8,
      ReflectanceOfRho = 9,
      ReflectanceOfRhoAngle = 10,
      TransmittanceOfAngle = 11,
      TransmittanceOfRho = 12,
      TransmittanceOfRhoAngle = 13,
      PMCAbsorptanceTotal = 14,
      PMCReflectanceOfRho = 15,
      PMCReflectanceOfRhoAngle = 16,
      PMCTransmittanceOfRho = 17,
      PMCTransmittanceOfRhoAngle = 18
  };
  enum class VirtualBoundaryType : uint32_t
  {
      None = 0,
      DiffuseReflectance = 1,       
      DiffuseTransmittance = 2,     
      SpecularReflectance = 3,      
      GenericVolumeBoundary = 4,    
      Dosimetry = 5,               
      PMCDiffuseReflectance = 6,   
      PMCDiffuseTransmittance = 7,  
      BoundingCylinderVolume = 8    
  };
```
![image](https://github.com/Neargye/magic_enum/assets/60612754/1403a7c8-c3ff-4f9f-a317-21b5f2cdd462)

**Comment by Neargye** [comment]
The new version will now have a static assert, and you can catch it at the compilation stage.
