### ISSUE TITLE
New include path format

### ISSUE THREAD

**Issue by cpsauer** [Neargye/magic_enum#310]
Hi @Neargye! Thanks again for a wonderful library.

I was looking at https://github.com/Neargye/magic_enum/commit/eb867ec9baaabc5b60816861923fdef53972cba2: is the intent to have users `#include "magic_enum/..."` (like for Bazel) or `#include "magic_enum.hpp"`, (like in the cmake config)?

Either seems totally reasonable, but I happened across the inconsistency when updating (and needing to change my includes), so I figured you might want a friendly heads.

Thanks for all you do,
Chris

**Comment by Neargye** [comment]
Hi,
~~I think `#include "magic_enum.hpp"`, I'll try to quickly fix it.~~
~~Thanks for catch and create issues~~

UPD:
In https://github.com/Neargye/magic_enum/pull/374 was added breaking changes, need to use `#include <magic_enum/magic_enum.hpp>` instead of `#include <magic_enum.hpp>`

**Comment by Neargye** [comment]
It seemed to me that I had configured this correctly in cmake this way `#include "magic_enum.hpp"`, but with so many build systems I’m already a little confused, could you tell me where I'm wrong?

**Comment by cpsauer** [comment]
Sorry--I wrote the path <-> build systems mappings backwards above, but they are indeed inconsistent. (Have edited the original post so I don't confuse any future readers, but it was previously wrong.) 

So to confirm: cmake is as you want, `#include "magic_enum.hpp"`. I'm seeing you made the parallel change for meson in https://github.com/Neargye/magic_enum/commit/3c92e9035bbddd2a56eae09a04b2e9f6d59c1372.  I've tossed up a quick PR #311 to make things consistent for Bazel (which is what I'm using and why I noticed). On a quick look, it seemed like those were all the build systems; if that's right #311 should resolve!

Thanks again for making a stupendous library and sharing it with the world!

**Comment by Neargye** [comment]
Thanks for your help!

**Comment by cpsauer** [comment]
My pleasure. Thanks again for being so great to work with, Daniil, and for putting in the work to share such a great library with the world.

**Comment by Neargye** [comment]
UPD:
In https://github.com/Neargye/magic_enum/pull/374 was added breaking changes, need to use `#include <magic_enum/magic_enum.hpp>` instead of `#include <magic_enum.hpp>`
