### ISSUE TITLE
Conan - magic_enum package is not easily reachable

### ISSUE THREAD

**Issue by souaso90** [Neargye/magic_enum#32]
The recipe given in the integration section of the README file to download the library using conan is not accurate:   

_"If you are using Conan to manage your dependencies, merely add magic_enum/x.y.z@neargye/stable to your conan's requires, where x.y.z is the release version you want to use."_

 The package is not available in conan-center, so nothing is found juste by following the previous steps. 

To make it work, I had to add @Neargye's personal [repository](https://api.bintray.com/conan/neargye/conan-packages) (found [in this closed issue #3](https://github.com/Neargye/magic_enum/issues/3)).

It would be great if the package is pushed to conan-center to make it easily accessible.

**Comment by Neargye** [comment]
Now, https://github.com/conan-io/conan-center-index/pull/1407 and https://github.com/conan-io/conan-center-index/pull/1864 closed, does this solve the issues?

**Comment by Neargye** [comment]
Hi @gocarlos!
Many thanks for help with Conan! I have a couple of questions, I'm still not experienced with Conan.
1. magic_enum and nameof now available in conan-center?
2. is it necessary `conanfile.py` in repo?

**Comment by gocarlos** [comment]
Hi @Neargye 

No its not necessary, though I'd add a link to the conan center (badges still not available) and change the readme to with the new dependency name

**Comment by Neargye** [comment]
@gocarlos If you want to do PR, I will be glad! Or I will do it myself later.

**Comment by Neargye** [comment]
@gocarlos  whats mean 'link to the conan center' ? `magic_enum/x.y.z` or another?

**Comment by gocarlos** [comment]
This : 
https://conan.io/center/magic_enum/0.6.6 

And

magic_enum/x.y.z
