### ISSUE TITLE
What would happen if this is used with an enum bitmask?

### ISSUE THREAD

**Issue by shreyasbharath** [Neargye/magic_enum#33]

**Comment by Neargye** [comment]
Enum value must be in range [MAGIC_ENUM_RANGE_MIN, MAGIC_ENUM_RANGE_MAX].
By default MAGIC_ENUM_RANGE_MIN = -128, MAGIC_ENUM_RANGE_MAX = 128.

Enum like:
```cpp
enum flag { 1, 2, 4, 8, 16, 32, 64, 128 }
```
Will be work without settings, for more large enum check [limitations](https://github.com/Neargye/magic_enum/blob/master/doc/limitations.md)

**Comment by shreyasbharath** [comment]
Thanks for the response!

What if you have something like this?

```cpp
enum class Status : uint32_t {
    BIT_0 = 1,
    BIT_1 = 2,
    BIT_2 = 4,
    BIT_3 = 8,
    ...
};
```

**Comment by Neargye** [comment]
BIT_9, BIT_10 and etc will not reflect.

**Comment by shreyasbharath** [comment]
Okay, thanks. Is it worth adding this to the limitations section?
