### ISSUE TITLE
Enum Range limitation : is range more than UINT16_MAX possible

### ISSUE THREAD

**Issue by Dadaduo** [Neargye/magic_enum#335]
enum class Color : uint32_t {
  alice_blue = 0xF0F8FF,               // rgb(240,248,255)
  antique_white = 0xFAEBD7,            // rgb(250,235,215)
  aqua = 0x00FFFF,                     // rgb(0,255,255)
  aquamarine = 0x7FFFD4,               // rgb(127,255,212)
  azure = 0xF0FFFF,                    // rgb(240,255,255)
  beige = 0xF5F5DC,                    // rgb(245,245,220)
  bisque = 0xFFE4C4,                   // rgb(255,228,196)
  black = 0x000000,                    // rgb(0,0,0)
};

color code ranges from 0x000000 to 0xFFFFFF. 
 is it possible to enlarge range limitation for this kind of case?

**Comment by Neargye** [comment]
Done in master.

**Comment by bxk-sonavex** [comment]
Should this item in the `limitations.md` be removed or revised?
> MAGIC_ENUM_RANGE = (MAGIC_ENUM_RANGE_MAX - MAGIC_ENUM_RANGE_MIN) must be less than UINT16_MAX.

**Comment by Neargye** [comment]
Yes, need to update

**Comment by ZXShady** [comment]
Hi, Be aware that compilation times will likely blow up your compiler with such a huge range so increasing the range isn't free.
