### ISSUE TITLE
getting wrong results

### ISSUE THREAD

**Issue by icyfox168168** [Neargye/magic_enum#338]
get IPPROTO_IGMP|IPPROTO_IPV4 why IPPROTO_TCP ？

IPPROTO_IGMP|IPPROTO_IPV4 = 6

IPPROTO_TCP value: 6

  auto f3 = magic_enum::enum_cast<IPPROTO>(Protocol);
                    if (f3.has_value()) {
                        std::cout << magic_enum::enum_flags_name(f3.value()) << " = " << magic_enum::enum_integer(f3.value()) << std::endl;
                    }

                    auto result = magic_enum::enum_cast<IPPROTO>("IPPROTO_TCP");
                    if (result.has_value())
                    {
                        std::cout << "IPPROTO_TCP value: " << result.value() << std::endl;
                    }

typedef enum {
#if(_WIN32_WINNT >= 0x0501)
    IPPROTO_HOPOPTS       = 0,  // IPv6 Hop-by-Hop options
#endif//(_WIN32_WINNT >= 0x0501)
    IPPROTO_ICMP          = 1,
    IPPROTO_IGMP          = 2,
    IPPROTO_GGP           = 3,
#if(_WIN32_WINNT >= 0x0501)
    IPPROTO_IPV4          = 4,
#endif//(_WIN32_WINNT >= 0x0501)
#if(_WIN32_WINNT >= 0x0600)
    IPPROTO_ST            = 5,
#endif//(_WIN32_WINNT >= 0x0600)
    IPPROTO_TCP           = 6,
#if(_WIN32_WINNT >= 0x0600)
    IPPROTO_CBT           = 7,
    IPPROTO_EGP           = 8,
    IPPROTO_IGP           = 9,
#endif//(_WIN32_WINNT >= 0x0600)
    IPPROTO_PUP           = 12,
    IPPROTO_UDP           = 17,
    IPPROTO_IDP           = 22,
#if(_WIN32_WINNT >= 0x0600)
    IPPROTO_RDP           = 27,
#endif//(_WIN32_WINNT >= 0x0600)

#if(_WIN32_WINNT >= 0x0501)
    IPPROTO_IPV6          = 41, // IPv6 header
    IPPROTO_ROUTING       = 43, // IPv6 Routing header
    IPPROTO_FRAGMENT      = 44, // IPv6 fragmentation header
    IPPROTO_ESP           = 50, // encapsulating security payload
    IPPROTO_AH            = 51, // authentication header
    IPPROTO_ICMPV6        = 58, // ICMPv6
    IPPROTO_NONE          = 59, // IPv6 no next header
    IPPROTO_DSTOPTS       = 60, // IPv6 Destination options
#endif//(_WIN32_WINNT >= 0x0501)

    IPPROTO_ND            = 77,
#if(_WIN32_WINNT >= 0x0501)
    IPPROTO_ICLFXBM       = 78,
#endif//(_WIN32_WINNT >= 0x0501)
#if(_WIN32_WINNT >= 0x0600)
    IPPROTO_PIM           = 103,
    IPPROTO_PGM           = 113,
    IPPROTO_L2TP          = 115,
    IPPROTO_SCTP          = 132,
#endif//(_WIN32_WINNT >= 0x0600)
    IPPROTO_RAW           = 255,

    IPPROTO_MAX           = 256,
//
//  These are reserved for internal use by Windows.
//
    IPPROTO_RESERVED_RAW  = 257,
    IPPROTO_RESERVED_IPSEC  = 258,
    IPPROTO_RESERVED_IPSECOFFLOAD  = 259,
    IPPROTO_RESERVED_WNV = 260,
    IPPROTO_RESERVED_MAX  = 261
} IPPROTO, *PIPROTO;

**Comment by icyfox168168** [comment]
The version of vcpkg I use

**Comment by Neargye** [comment]
try `magic_enum::enum_name(f3.value())`

**Comment by ZXShady** [comment]
Hi, this is expected behavior not a bug in magic_enum.

The Issue: The `IPPROTO` enum defines mutually exclusive protocol numbers (e.g., IGMP=2, IPV4=4, TCP=6). They are not bit flags and should never be combined with operator `|`.

The operation `IPPROTO_IGMP | IPPROTO_IPV4` performs a bitwise or 2 | 4 = 6. which is the value of `IPPROTO_TCP`. magic_enum correctly maps the integer 6 to the `IPPROTO_TCP` enum value.

To fix this, make them flags, Those protocol numbers you had are singular choices. If you need combinable flags 

```cpp
enum class Protocol {
    IGMP = 1 << 0,
    IPv4 = 1 << 1,
    TCP  = 1 << 2
};
// Use magic_enum::enum_flags_name with this enum instead.

// Also don't forget to tell magic_enum that it is a bitflag!
template<>
struct enum_range
{
   static constexpr bool is_flags = true;
};
```

Youe current code was misusing the enum. magic_enum is working correctly by finding the enum member that matches the integer value you provided.
