### ISSUE TITLE
Intellisense hangs forever when using magic_enum since 0.6.1 on x86 projects

### ISSUE THREAD

**Issue by albertvaka** [Neargye/magic_enum#34]
Ctrl+clicking on anything in my project stalls waiting for intellisense to complete if I include magic_enum 0.6.1 or newer. Version 0.6.0 doesn't have this problem.

**Edit**: Only happens on 32bit projects.

Tested in Visual Studio 2019 and Visual Studio 2017.

**Comment by albertvaka** [comment]
Created a single-file project that reproduces the problem:

[Project1.zip](https://github.com/Neargye/magic_enum/files/4364167/Project1.zip)

**Comment by Neargye** [comment]
Thanks for example, I will check this.

**Comment by Gringoniceguy** [comment]
i have same issue

**Comment by Neargye** [comment]
@albertvaka @Gringoniceguy could you please check this version? [magic_enum.zip](https://github.com/Neargye/magic_enum/files/4414495/magic_enum.zip)

**Comment by albertvaka** [comment]
It seems to still have the issue :( Thanks a lot for looking into this, though :D

**Comment by Gringoniceguy** [comment]
I think this might not be a issue with the magic_enum but with vs i am gonna report this too microsoft

**Comment by albertvaka** [comment]
Makes sense, taking into account it works everywhere else. It's still annoying when trying to use magic_enum  with MSVC, though. Maybe it can be stated as a known issue so people can stay on 0.6.0 if they target x86 on MSVC?

**Comment by Neargye** [comment]
I still could not achieve good work on x86, it seems that there is simply not enough memory for complex templates.

Added a description of this problem in limitations.

**Comment by Neargye** [comment]
@albertvaka @Gringoniceguy could you please check this version? 
[magic_enum.zip](https://github.com/Neargye/magic_enum/files/4662293/magic_enum.zip)

**Comment by albertvaka** [comment]
Looks like its working 👏

**Comment by Neargye** [comment]
Thanks @albertvaka, will add this to the new release.

**Comment by albertvaka** [comment]
Nice! What was the fix in the end?

**Comment by Neargye** [comment]
It was necessary to rewrite the order of calculation of values ​​and caching of arrays.

**Comment by Neargye** [comment]
Fix in master branch
