### ISSUE TITLE
enum_contains occur error when number excceed 127

### ISSUE THREAD

**Issue by yuekeyuans** [Neargye/magic_enum#345]
``` c++
enum class A {
    a = 127,
    b = 128
};

int main()
{
    std::cout << magic_enum::enum_contains<A>(127);    // output 1
    std::cout << magic_enum::enum_contains<A>(128);    // output 0
}
```
as above, the second line out put ought to be 1(true), but produce 0 (false) value.

can you fix this bug?

**Comment by alexkaratarakis** [comment]
This is a limitation, you can read more about it here: https://github.com/Neargye/magic_enum/blob/master/doc/limitations.md#enum-range
You can customize the allowed range globally (for all enums) or individually per enum.

**Comment by yuekeyuans** [comment]
thank you, I see it.
this really helps me a lot
