### ISSUE TITLE
did something happen to magic_enum::enum_for_each ?

### ISSUE THREAD

**Issue by mishaxz** [Neargye/magic_enum#348]
stupid question but is `magic_enum::enum_for_each` still part of of the library? 

my old code is refusing to compile because it thinks `enum_for_each` is not a member of `magic_enum`

and I can't really find `enum_for_each` in the code on this site.

**Comment by Neargye** [comment]
Hi,
try `#include "magic_enum_utility.hpp`

**Comment by mishaxz** [comment]
thanks that worked
