### ISSUE TITLE
Enhancement: Optional comparison predicate for enum_cast(std::string_view value) [case-insensitive, etc]

### ISSUE THREAD

**Issue by jbhelm** [Neargye/magic_enum#35]
It would be useful to optionally pass a comparison predicate to use for the equality comparison in `enum_cast(std::string_view value)`. In my case, I'd like to perform case-insensitive comparisons.

**Comment by Neargye** [comment]
Yes, good idea

**Comment by Neargye** [comment]
@jbhelm update in master.
Now it's work 
```cpp
enum_cast<Color>("blue", [](char lhs, char rhs) { return std::tolower(lhs) == std::tolower(rhs); }).value() == Color::BLUE
```

**Comment by jbhelm** [comment]
Thanks! I tried it out, works great for my use case.
