### ISSUE TITLE
Support for C++11

### ISSUE THREAD

**Issue by rhvarrier** [Neargye/magic_enum#359]
Is there any plans to add support for C++11 even if it's limited to some functionalities.

**Comment by Neargye** [comment]
Unfortunately, this library uses many features from C++17 (inline constexpr, string_view, etc); I don’t see it possible to rewrite it in C++11.

**Comment by ZXShady** [comment]
> Unfortunately, this library uses many features from C++17 (inline constexpr, string_view, etc); I don’t see it possible to rewrite it in C++11.

Well it is possible if you are willing to make your entire library functions on a single line with 17 nested ternaries 😛
