### ISSUE TITLE
Construct bitset from string_view

### ISSUE THREAD

**Issue by asolwa** [Neargye/magic_enum#366]
Hi,

It appears a bug has crept into the construction of the bitset. The set function is used, but it does not accept std::optional. The result of the 'enum_cast' function should be dereferenced before being passed to the set method.

https://github.com/Neargye/magic_enum/blob/664ee62c12570948b0e025d15b42d641fba8d54a/include/magic_enum/magic_enum_containers.hpp#L624

Fixed in:
https://github.com/Neargye/magic_enum/pull/367

**Comment by Neargye** [comment]
Thanks for fix!
