### ISSUE TITLE
Pollutes /usr/local/include install directory with too many headers

### ISSUE THREAD

**Issue by JWCS** [Neargye/magic_enum#377]
I was starting to use this library, and I noticed that there's like 10x of `magic_enum*.hpp` files in the /usr/local/include directory on local install. Most other projects either install one singular header to that directory, or they install into a project-wrapping folder. 
Would it be possible to reduce 
```
/usr/local/include# ls magic_enum*
magic_enum.hpp             magic_enum_flags.hpp   magic_enum_iostream.hpp
magic_enum_all.hpp         magic_enum_format.hpp  magic_enum_switch.hpp
magic_enum_containers.hpp  magic_enum_fuse.hpp    magic_enum_utility.hpp
```
To:
```
magic_enum.hpp   # For backwards compatibility
magic_enum/
| - magic_enum.hpp
| - all.hpp
| - containers.hpp
....
```
? (Or something similar?)

(Note: I was locally installing this off of master, for the bugfix, and with patch #374, using cmake install )

**Comment by Neargye** [comment]
Fixed in https://github.com/Neargye/magic_enum/pull/374
@JWCS thanks for testing!
