### ISSUE TITLE
Runtime Reflection?

### ISSUE THREAD

**Issue by stellarpower** [Neargye/magic_enum#384]
Hi,

I need to access information about enums in a runtime manner. I am performing compile-time reflection stuff in a library, and the I use that in an application, so that I need only rebuild the library each time (much quicker). Whilst it's great to be able to do stuff constexpr, sometimes we need to access information in a purely runtime manner, and so I think it might be a nice complement to the library to have that in (batteries included).

Obviously it's not too hard to knock up an abstract base class and inherit, filling out enum information, and then register that with some sort of factory oneself. But I'm wondering if it's a common-enough usecase that it would be worth adding a class for it within magic_enum so there's no need to roll your own.

I only need the basics myself, probably just a container of values and string pairs, and I expect something more thorough might be desired if it were to be included in the repository. But I'd happily throw what I end up writing into a gist and adding a link.

Thanks

**Comment by Neargye** [comment]
I think you can try https://github.com/aantron/better-enums

**Comment by ZXShady** [comment]
Hi,

This sadly isn't really possible as magic_enum requirex compile time to even work. it iterates at compile time to find the possible enums and this is not something it can make runtime, (actually it can it will just blow up your binary size massively due to all the strings it needs)

However you can use "extern template" to avoid reinstantating a template again and again.

```cpp
// your cpp file
#include "header.hpp"
template void magic_enum::enum_names<Enum>();
template void magic_enum::enum_entries<Enum>();
template void magic_enum::enum_values<Enum>();
```

header file
```cpp
enum Enum {...}

// note "extern"
extern template auto magic_enum::enum_names<Enum>();
extern template auto magic_enum::enum_entries<Enum>();
extern template auto magic_enum::enum_values<Enum>();
```
