### ISSUE TITLE
GCC 8.2 support

### ISSUE THREAD

**Issue by mintyc** [Neargye/magic_enum#4]
With imminent versions of centos, Ubuntu etc still on GCC 8.x stream, consider a workaround for the issues preventing GCC 8 support.

The patches to GCC 8 compiler to fix the issues aren't really possible to use either for a lot of organisations or individuals.

**Comment by Neargye** [comment]
`magic_enum` use intrinsics - namely `PRETTY_FUNCTION`, on `GCC < 9` `PRETTY_FUNCTION` not can get name enum.

At the moment I do not know how to make support `GCC < 9`.

**Comment by JuliusRapp** [comment]
`magic_enum` could provide some code-generation utility. Modern compilers then can always use the current technique to "reflect" the enums. Library developers can use the code-generation utility to emit the fallback code for non-modern compilers. The fallback code can also be included by modern compilers (in order to detect consistency issues, i.e. the need to re-generate the fallback code).

I do not have any capacity for contributing polished code, but I played around with this idea and just wanted to share this idea and [my hack](https://github.com/JuliusRapp/magic_enum/commit/8bdc41abc955f4a8f5b20c1d3efe51ce850424f8).

Thanks for this awesome tool. Keep it up!

**Comment by Neargye** [comment]
I’m a bit busy at work right now, but I’m sure to try playing with your offer.

Maybe for generating enum data for non-modern compilers recommend using https://github.com/aantron/better-enums?

**Comment by Neargye** [comment]
Hi @JuliusRapp could you describe your idea in more detail?
on non-modern generate_enum_fallbacks will not work because enum_entries will return an empty array.

**Comment by JuliusR** [comment]
> on non-modern generate_enum_fallbacks will not work because enum_entries will return an empty array.

Yes, it is correct that `generate_enum_fallbacks` will not work on, say, GCC 8. In fact, I prefer a compile-time error in that case, and that is what I used in my hack. Anyway, sorry for not providing any usage hints. Here the procedure I have in mind:

1. Use a fully supported compiler (say, GCC 9) to generate the fallback code.
2. Include the fallback code.
3. Use non-modern compiler (say, GCC 8) with `magic_enum` as you wish: the fallback code is automatically used if the usual detection fails.

Here is a small usage example. The `static_assert`s are passed with [GCC 8 on godbolt.org](https://godbolt.org/z/ipkoEZ).

```
#include <iostream>
#include <string_view>
#include <utility>

#include <https://raw.githubusercontent.com/JuliusRapp/magic_enum/scratch-gcc8-fallback/include/magic_enum.hpp>

enum Color { RED = 2, BLUE = 4, GREEN = 8 };

////////////////////////////////////////////////////////////////////////////////
//
// The following code has been generated by a fully supported compiler (GCC 9).
// After code generation, the code was manually pasted here. If the flag is set
// then a couple of older compilers (tested with GCC 8) should support all
// functionality provided by `magic_enum`.
//
////////////////////////////////////////////////////////////////////////////////
#if USE_GENERATED_CODE_FOR_FALLBACK
////////////////////////////////////////////////////////////////////////////////

// Mark this enum as fallback-enabled.
// This overload prevents a compile-time error.
template<Color V> constexpr std::string_view enum_name_fallback(
  std::integral_constant<
    Color, V
  >
) { return {}; }

// Provide better overloads for all known enums values.
constexpr std::string_view enum_name_fallback(std::integral_constant<Color, Color::RED>) { return "RED"; }
constexpr std::string_view enum_name_fallback(std::integral_constant<Color, Color::BLUE>) { return "BLUE"; }
constexpr std::string_view enum_name_fallback(std::integral_constant<Color, Color::GREEN>) { return "GREEN"; }

////////////////////////////////////////////////////////////////////////////////
#endif
////////////////////////////////////////////////////////////////////////////////

int main() {
// If the flag is set then all the following checks succeed with GCC8.
  constexpr auto color_entries = magic_enum::enum_entries<Color>();
  using P = std::pair<Color, std::string_view>;
  static_assert(color_entries[0] == P{Color::RED, "RED"});
  static_assert(color_entries[1] == P{Color::BLUE, "BLUE"});
  static_assert(color_entries[2] == P{Color::GREEN, "GREEN"});

  // The following line can be used to update the generated code. Note that a
  // fully supported compiler has to be used for code generation. However, it is
  // possible to add some consistency checks for older compilers (verifying
  // some necessary but non-sufficient conditions that the generated code is
  // up-to-date).
//  std::cout << magic_enum::generate_enum_fallbacks<Color>() << std::endl;
}

```

I believe that the syntax of the fallback code can be optimized to reduce the noise. Maybe a single `switch` with all enum values is most readable.

**Comment by JuliusRapp** [comment]
> on non-modern generate_enum_fallbacks will not work because enum_entries will return an empty array.

Yes, it is correct that `generate_enum_fallbacks` will not work on, say, GCC 8. In fact, I prefer a compile-time error in that case, and that is what I used in my hack. Anyway, sorry for not providing any usage hints. Here the procedure I have in mind:

1. Use a fully supported compiler (say, GCC 9) to generate the fallback code.
2. Include the fallback code.
3. Use non-modern compiler (say, GCC 8) with `magic_enum` as you wish: the fallback code is automatically used if the usual detection fails.

Here is a small usage example. The `static_assert`s are passed with [GCC 8 on godbolt.org](https://godbolt.org/z/ipkoEZ).

```
#include <iostream>
#include <string_view>
#include <utility>

#include <https://raw.githubusercontent.com/JuliusRapp/magic_enum/scratch-gcc8-fallback/include/magic_enum.hpp>

enum Color { RED = 2, BLUE = 4, GREEN = 8 };

////////////////////////////////////////////////////////////////////////////////
//
// The following code has been generated by a fully supported compiler (GCC 9).
// After code generation, the code was manually pasted here. If the flag is set
// then a couple of older compilers (tested with GCC 8) should support all
// functionality provided by `magic_enum`.
//
////////////////////////////////////////////////////////////////////////////////
#if USE_GENERATED_CODE_FOR_FALLBACK
////////////////////////////////////////////////////////////////////////////////

// Mark this enum as fallback-enabled.
// This overload prevents a compile-time error.
template<Color V> constexpr std::string_view enum_name_fallback(
  std::integral_constant<
    Color, V
  >
) { return {}; }

// Provide better overloads for all known enums values.
constexpr std::string_view enum_name_fallback(std::integral_constant<Color, Color::RED>) { return "RED"; }
constexpr std::string_view enum_name_fallback(std::integral_constant<Color, Color::BLUE>) { return "BLUE"; }
constexpr std::string_view enum_name_fallback(std::integral_constant<Color, Color::GREEN>) { return "GREEN"; }

////////////////////////////////////////////////////////////////////////////////
#endif
////////////////////////////////////////////////////////////////////////////////

int main() {
// If the flag is set then all the following checks succeed with GCC8.
  constexpr auto color_entries = magic_enum::enum_entries<Color>();
  using P = std::pair<Color, std::string_view>;
  static_assert(color_entries[0] == P{Color::RED, "RED"});
  static_assert(color_entries[1] == P{Color::BLUE, "BLUE"});
  static_assert(color_entries[2] == P{Color::GREEN, "GREEN"});

  // The following line can be used to update the generated code. Note that a
  // fully supported compiler has to be used for code generation. However, it is
  // possible to add some consistency checks for older compilers (verifying
  // some necessary but non-sufficient conditions that the generated code is
  // up-to-date).
//  std::cout << magic_enum::generate_enum_fallbacks<Color>() << std::endl;
}

```

I believe that the syntax of the fallback code can be optimized to reduce the noise. Maybe a single `switch` with all enum values is most readable.

**Comment by Neargye** [comment]
Can use macros to generate fallback code.

**Comment by Neargye** [comment]
But honestly, I don’t like this solution, it contradicts the original idea - reflection without additional code.

**Comment by JuliusRapp** [comment]
> But honestly, I don’t like this solution, it contradicts the original idea - reflection without additional code.

Yes, I understand that. My fallback suggestion was just meant to provide an intermediate solution for older compilers. Once old-compiler support can be dropped, the fallback is no longer required. I still see advantages of this hybrid solution: (1) no macros required and (2) fully supported compilers can use reflection in order to guarantee correctness. As an alternative to my hack, the syntax could be as readable as
```
enum Color { RED = 2, BLUE = 4, GREEN = 7 };

#if MAGIC_ENUM_USE_FALLBACK
constexpr std::string_view magic_enum_fallback(Color V) {
  switch(V) {
  case Color::RED: return "RED";
  case Color::BLUE: return "BLUE";
  case Color::GREEN: return "GREEN";
  }
  return "";
}
#endif
```
Once again, let me point out that I really understand your argument concerning the _original idea_ of `magic_enum`. It is just the "help wanted" label that made me propose the fallback solution.

---

Do you like the idea of a compile-time error if `magic_enum` is used with unsupported compilers? In addition, `magic_enum` could provide traits to check for compiler support. I prefer that over a silent failure on, say, GCC 8.

**Comment by Neargye** [comment]
Yes, I like the idea `compile-time error`, soon I add error and traits to check compiler support. For now, add https://github.com/Neargye/magic_enum/blob/2e61a86b2f2a8bf14b70180e4e99613a9b91bd51/include/magic_enum.hpp#L136.

About fallback I think I need to think more.

**Comment by Neargye** [comment]
Add compile-time error and traits to check for compiler support - check dev, feel free give feedback.
