### ISSUE TITLE
doesn't appear in latest VCPKG

### ISSUE THREAD

**Issue by jjpepper** [Neargye/magic_enum#44]
vcpkg search magic_enum yields nothing with latest vcpkg.  The readme says it should be in vcpkg.  What's going on?

**Comment by jjpepper** [comment]
It's actually magic-enum.  The readme could be clearer by making the link text pointing to the magic-enum vcpkg portfile actually be called `magic-enum` and not `magic_enum`.

**Comment by Neargye** [comment]
Thank you for your issues. Corrected the description in readme.
