### ISSUE TITLE
Please improve compatibility with "degraded" C++17

### ISSUE THREAD

**Issue by gjasny** [Neargye/magic_enum#45]
Hello,

I'd like to use magic_enum on macOS but unfortunately I have to keep backward compatibility to an older 10.9 release.
That makes things like `std::optional` unavailable:

```
PacketParser.cpp:381:33: error: 'value' is unavailable: introduced in macOS 10.14
                    reasonBits).value();
```

I could see three ways of working around:

1. Provide `enum_foo_or_throw()` methods which completely avoid using `std::optional` and throw instead.
2. Provide your own `optional` implementation (like better enums does).
3. Provide a way to switch to `boost::optional` instead of `std::optional`

Thanks,
Gregor

**Comment by Neargye** [comment]
Check https://github.com/Neargye/magic_enum/tree/using_optional/include

```cpp
#include <boost/optional.hpp>

#define MAGIC_ENUM_USING_ALIAS_OPTIONAL using boost::optional;
#include <magic_enum.hpp>
```

It looks a little strange, but it seems that this is what will be optimal.

**Comment by Neargye** [comment]
https://github.com/TartanLlama/optional or https://github.com/martinmoene/optional-lite as boost::optional alternative

**Comment by Neargye** [comment]
Or this syntax

```cpp
#include <boost/optional.hpp>

#define MAGIC_ENUM_USING_ALIAS_OPTIONAL boost::optional
#include <magic_enum.hpp>
```

**Comment by gjasny** [comment]
I had to replace `std::nullopt` with `{}` and also add a missing `<string>` header. Afterwards it worked fine.

**Comment by Neargye** [comment]
@gjasny fix in master

Here example of using
```cpp
#include <boost/optional.hpp>
#include <string> // include if need
#define MAGIC_ENUM_USING_ALIAS_OPTIONAL using boost::optional;
#include <magic_enum.hpp>
```

**Comment by l16i** [comment]
@Neargye I continue on this issue since it seems that your solution doesn't work anymore.
The namespace `fusion_detail` doesn't use the `MAGIC_ENUM_USING_ALIAS_OPTIONAL` macro as we can see here:
``` c++
namespace fusion_detail {

template <typename E>
constexpr std::optional<std::uintmax_t> fuse_one_enum(std::optional<std::uintmax_t> hash, E value) noexcept {
  if (hash.has_value()) {
    if (const auto index = enum_index(value); index.has_value()) {
      // Add 1 to prevent matching 2D fusions with 3D fusions etc.
      return (hash.value() << detail::log2(enum_count<E>() + 1)) | (index.value() + 1);
    }
  }
  return std::nullopt;
}

template <typename E>
constexpr std::optional<std::uintmax_t> fuse_enum(E value) noexcept {
  return fuse_one_enum(0, value);
}

template <typename E, typename... Es>
constexpr std::optional<std::uintmax_t> fuse_enum(E head, Es... tail) noexcept {
  return fuse_one_enum(fuse_enum(tail...), head);
}

}
```
It use `std::optional` instead of `optional`

**Comment by Neargye** [comment]
@laurentNoudohounsi please create another issue. 
work with the fusion is still in progress, I can suggest using the release version.

**Comment by l16i** [comment]
> @laurentNoudohounsi please create another issue. work with the fusion is still in progress, I can suggest using the release version.

Thanks it works now
