### ISSUE TITLE
Constexpr must be initialized by constant expression error VxWorks

### ISSUE THREAD

**Issue by switch623** [Neargye/magic_enum#46]
Hello,

I am currently using C++17 with LLVM clang version 9.0.1.1 in a VxWorks environment and when I attempt to compile example/example.cpp I am prompted with (along with many other constexpr variables):

```
magic_enum.hpp:281:23: Error: constexpr variable 'values_v<Color>' must be initialized by a constant expression.
inline constexpr auto values_v = values<E>(std::make_integer_sequence<int, range_size<E, reflected_min_v<E>, reflected_max_v<E>>()>{});
```

I have the latest version of Magic_Enum and to my understanding, it's supposed to work with clang >=5. 

Thank you very much for your work, please let me know if I can provide more info.

**Comment by Neargye** [comment]
Hi, 
Could you please send result command clang --version?

**Comment by switch623** [comment]
Hi,
Clang version 9.0.1.1
This may be unique to the Windriver VxWorks environment.

**Comment by Neargye** [comment]
Could you please recheck on the latest master?
I fix https://github.com/Neargye/magic_enum/issues/53, looks similar.

**Comment by switch623** [comment]
Hello, 
I rechecked on the latest master and was given:
`magic_enum.hpp:440:23: error: constexpr variable 'values_v<Color, false>' must be initialized by a constant expression.
inline constexpr auto values_v = values<E, IsFlags>();`
