### ISSUE TITLE
Enchancement: custom enum names

### ISSUE THREAD

**Issue by mhbackes** [Neargye/magic_enum#47]
Hi, thanks for doing a great job with this library.

`magic_enum` works amazingly well in most of the cases, but sometimes, the string conversion must be different from the enum value identifier.

For example, I would like to be able to convert the enum value `Red` to `"the red color"` instead of `"Red"` and also convert `"the red color"` back to `Red`. That's not possible in the current version of `magic_enum` as far as I know.

Better Enums has an alternative for this, which is depicted in the example https://github.com/aantron/better-enums/blob/master/example/5-map.cc

Would it be possible to add a feature that allows custom definitions of names for enum values?

**Comment by Neargye** [comment]
Hi,

Now registering сustom enum name does not look so convenient, but it is possible in the current version.

```cpp
namespace neargye::detail {
  template <>
  constexpr auto n<Color, Color::RED>() noexcept {
    return std::string_view{"the red color"};
  }

  template <>
  constexpr auto n<Color, Color::BLUE>() noexcept {
    return std::string_view{"the red blue"};
  }
}
```


It might be worth adding a macro to register names.

**Comment by mhbackes** [comment]
Interesting, thanks for the quick response.

**Comment by Neargye** [comment]
@mhbackes 
Add example in the master.
You can test this functionality. If you have any ideas on how to improve the overload syntax, open a new issues.
