### ISSUE TITLE
Better syntax for custom enum names

### ISSUE THREAD

**Issue by mhbackes** [Neargye/magic_enum#50]
Following up #47.

I'm not really happy with the current syntax for defining custom enum names, specially because you need to deal with functions defined in the namespace `detail` which does not seem right. Furthermore, a function named `n` is not a very intuitive name for people using the library.

Threrefore, I have 2 suggestions on how to improve it:
1. Add a function `template <auto V> std::string_view magic_enum::custom_name()` to the API:
```c++
template <auto V>
constexpr std::string_view magic_enum::custom_name() noexcept { return ""; }
...
// a small change in `n()`
template <typename E, E V>
std::string_view magic_enum::n() { 
  if constexpr (auto s = custom_name<V>(); !s.empty())
    return s;
  else {
    ... // current `n()` implementation
  }
}
...
// example of usage
template <>
constexpr std::string_view magic_enum::custom_name<Color::red> noexcept { return "the red color"; }
```

Pros:
* Removed redundant template parameter `typename E`.
* Specialization defined using a function defined in `magic_enum`, not in `magic_enum::detail`
* Intuitive function name `custom_name` instead of `n`.

Cons:
* The `if constexpr` in `n()` is a bit ugly...
* Very verbose if you compare with option 2.

2. Use a macro (as suggested by @Neargye in #47):
```c++
#define MAGIC_ENUM_CUSTOM_NAME(VALUE, TEXT) \
template <> constexpr auto magic_enum::detail::n<decltype(VALUE), VALUE>() noexcept { return std::string_view{TEXT}; }
...
// example of usage
MAGIC_ENUM_CUSTOM_NAME(Color::red, "the red color")
```
Pros:
* Simpler syntax.

Cons:
* Its a macro... ¯\\_(ツ)_/¯
* It might not be clear that you cannot declare it inside a `class`/`namespace`.

Let me know what you think.

**Comment by Neargye** [comment]
@mhbackes 

> It might not be clear that you cannot declare it inside a class/namespace.

Is this functionality really necessary? First, it will clog the user class/namespace. Secondly, there may be some bad with ADL.

**Comment by mhbackes** [comment]
@Neargye, no, definitely not.

I'm just saying that if this is ever added to the API, it should be clear (in the documentation) that the macro should not be used inside class/namespaces.

**Comment by Neargye** [comment]
@mhbackes  how about this https://github.com/Neargye/magic_enum/blob/e7309583de648bae5a4405a422c8912ce963a114/example/example_custom_name.cpp

**Comment by Neargye** [comment]
Meh, vs2017 not work with this. It looks like I will implement macro

**Comment by Neargye** [comment]
```cpp
template <>
constexpr auto magic_enum::customize::enum_name<Color>(Color value) noexcept {
  switch (value) {
    case Color::RED:
      return std::string_view{"the red color"};
    case Color::BLUE:
      return std::string_view{"The BLUE"};
  }
  return std::string_view{}; // "Empty string for default or unknow value."
}
```

or 
```cpp
MAGIC_ENUM_CUSTOM_NAME(Color::RED, "the REDcolor")
MAGIC_ENUM_CUSTOM_NAME(Color::BLUE, "the BLUEcolor")
```

**Comment by Neargye** [comment]
```
// The reason for using a function is that a switch statement is, I believe, the
// only place where a compiler will check for exhaustiveness. If you forget to
// create a case for one of the enum's constants, the compiler can let you know.
```

Hm, maybe the switch option will be better.

**Comment by Neargye** [comment]
@mhbackes you can check to customize branch https://github.com/Neargye/magic_enum/tree/customize.

I think to highlight everything in a separate namespace for customization. is this a normal name `namespace magic_enum::customize`?

**Comment by mhbackes** [comment]
@Neargye, sounds amazing.

I think the switch case is indeed the best option. This should work really well. Thanks!

**Comment by mhbackes** [comment]
One last question (very minor detail): does the function need to be `auto`?
```cpp
template <>
constexpr std::string_view magic_enum::customize::enum_name<Color>(Color value) noexcept {
  switch (value) {
    case Color::RED:
      return "the red color"; // instead of `return std::string_view{"the red color"};`
    case Color::BLUE:
      return "The BLUE"; // instead of `return std::string_view{"The BLUE"};`
  }
  return ""; // instead of `return std::string_view{};`
}
```
I feel like declaring `std::string_view` as return gives a slight easier syntax.

**Comment by Neargye** [comment]
Yes.
I think I'll correct the syntax before taking it to the master.

**Comment by Neargye** [comment]
update in master
