### ISSUE TITLE
Can you add mingw support?

### ISSUE THREAD

**Issue by hadjTahar** [Neargye/magic_enum#51]

**Comment by Neargye** [comment]
Hi @Berrima, local tests show that magic_enum already working on mingw.

Could you please test too?

**Comment by hadjTahar** [comment]
Here is the code sample and the compiler output when I use Mingw32/64, I am using Qt creator IDE and works fine when using MSVC2017, hope that's helpful.

`

    #include <iostream>
    #include "magic_enum.hpp"
    
    
    class Test
    {
    public:
        enum class Color { RED = 2, BLUE = 4, GREEN = 8 };
    
        void doTest()
        {
            Color color = Color::RED;
            auto color_name = magic_enum::enum_name(color);
            std::cout  <<  color_name;
        }
    };
    
    
    
    int main(int , char *[])
    {
        Test tst;
        tst.doTest();
        return 0;
    }

`

![Capture1](https://user-images.githubusercontent.com/8595889/96042142-45311200-0e6d-11eb-924c-cb81a635f9dc.PNG)

**Comment by Neargye** [comment]
@Berrima 
Could you please tell which versions you are using?

**Comment by hadjTahar** [comment]
Hi Neargye,

I am using Mingw v 7.3.0, it comes with Qt 5.14 installation in the Windows version.

**Comment by Neargye** [comment]
Mingw  version must be 9.1 or higher.

**Comment by hadjTahar** [comment]
Yes, it works with 9.2.0, I just got used to the version that Qt installer supplies and I never bothered to check.

**Comment by Neargye** [comment]
Update readme, add Mingw version
