### ISSUE TITLE
Trait for checking if enum fits allowed range

### ISSUE THREAD

**Issue by mateuszzz88** [Neargye/magic_enum#55]
I need constexpr check that will tell me if for given enum, magic_enum will work:
```
template <typename EnumT>
(...)
EnumT v = ....;
(...)
        if constexpr (magic_enum::is_magic_enum_supported && magic_enum::is_supported_enum_v<EnumT>) {
            return format_to(ctx.out(), "{}", magic_enum::enum_name(v));
        } else {
            return format_to(ctx.out(), "{}", (int) v);
        }
```
Specifically `EnumT` in above code may have values outside scope of MAGIC_ENUM_RANGE_MIN, MAGIC_ENUM_RANGE_MAX

**Comment by Neargye** [comment]
You can do this in the following ways. 
```cpp
        if (magic_enum::enum_contains(v)) {
            return format_to(ctx.out(), "{}", magic_enum::enum_name(v));
        } else {
            return format_to(ctx.out(), "{}", (int) v);
        }
```

this will be work in constexpr  and in runtine

**Comment by Neargye** [comment]
If EnumT  may have values outside min_max range, magic_enum can't detect this(

**Comment by mateuszzz88** [comment]
I started searching for this because I had some compilation problems with "big enums". Strangely I am unable to produce minimal example for those problems. Anyway, 
```if constexpr (magic_enum::is_magic_enum_supported && magic_enum::detail::count_v<EnumT> > 0)``` seems to work for me. I borrowed count_v > 0 check from static assert that was triggering for me. 
I confess that I am not certain what exactly am I checking - can this work reliably?

**Comment by Neargye** [comment]
Yes, I understand your problem now, I will think about what functionality to add to solve it easier.

Now I offer the following solution, which does not look very nice, but it is reliable
```cpp
if constexpr (magic_enum::is_magic_enum_supported && magic_enum::detail::count_v<EnumT> > 0) {
  if (const auto s = magic_enum::enum_name(v); !s.empty()) {
    return format_to(ctx.out(), "{}", s);
  }
}
return format_to(ctx.out(), "{}", magic_enum::enum_integer(v));
```

**Comment by Neargye** [comment]
Fix in master, now check magic_enum::detail::count_v not need
```cpp
if constexpr (magic_enum::is_magic_enum_supported) {
  if (const auto s = magic_enum::enum_name(v); !s.empty()) {
    return format_to(ctx.out(), "{}", s);
  }
}
return format_to(ctx.out(), "{}", magic_enum::enum_integer(v));
```
