### ISSUE TITLE
Unexpected codegen with gcc 9.3 for a small enum

### ISSUE THREAD

**Issue by jh0x** [Neargye/magic_enum#57]
https://godbolt.org/z/vchq9h

**Comment by Neargye** [comment]
This is some kind of strange GCC problem, I do not yet know how to get around this, except how to advise not to use global constexpr variables.

**Comment by Neargye** [comment]
To fix this, need try not to use name values ​​as C-strings. 
After all, magic_enum is a C++17 library!

```cpp
int idx(const char* c) {
    for(size_t i = 0; i != arr.size(); ++i) {
        if (arr[i].compare(c) == 0) return i; // <-- work as std::string_view
    }
    return -1;
}
```
```cpp
auto enum_value = enum_cast<C>("AAAA").value();
auto idx = enum_index(enum_value ).value(); // <-- use only magic_enum
```

https://godbolt.org/z/s1Pz9s
