### ISSUE TITLE
Released to vcpkg?

### ISSUE THREAD

**Issue by ga2k** [Neargye/magic_enum#58]
Hi, the newest version hasn't been sent to vcpkg yet. That caused me a heart attack! Namespace customize doesn't exist in the old version.

**Comment by Neargye** [comment]
Hi, will prepare a new release soon.

**Comment by Neargye** [comment]
https://github.com/microsoft/vcpkg/pull/14046

**Comment by Neargye** [comment]
Version on vcpkg updated.
