### ISSUE TITLE
Convenient way to heck if bitmask contains enum flag

### ISSUE THREAD

**Issue by egorodet** [Neargye/magic_enum#63]
It would be nice to have a convenient way to check if the bitmask value contains enum flag, for example:
```cpp
enum class AnimalFlags : std::uint64_t { None = 0, HasClaws = 1 << 0, CanFly = 1 << 1, EatsFish = 1 << 2, Endangered = 1 << 3 };
using namespace magic_enum::bitwise_operators;
AnimalFlags animal_mask = AnimalFlags::HasClaws | AnimalFlags::CanFly;
if (animal_mask & AnimalFlags::CanFly) // compiler error here
    std::cout << "This animal can fly!";
```
This won't compile because there's no auomatic `enum class` casting to `bool` or `uint64_t`, so it won't compile without proper casting or comparison against `0` enum value of the bitwise expression result:
```cpp
if (static_cast<uint64_t>(animal_mask & AnimalFlags::CanFly))
    std::cout << "This animal can fly!";
```
or
```cpp
if ((animal_mask & AnimalFlags::CanFly) != AnimalFlags::None)
    std::cout << "This animal can fly!";
```
Would it be possible to support this use-case out of the box and provide more convenient way to check that bitmask contains particular flag? Maybe add a helper function `magic_enum::empty(mask)`, for example:
```cpp
if (!magic_enum::empty(animal_mask & AnimalFlags::CanFly))
    std::cout << "This animal can fly!";
```

**Comment by Neargye** [comment]
You can use API from 'magic_enum::flags', `magic_enum::flags::enum_contains(animal_mask & AnimalFlags::CanFly)`

exapmle: https://wandbox.org/permlink/H6Mey6SdLKwJ5sno

**Comment by egorodet** [comment]
Cool! Did not notice that it's already available. The only problem is that it's a little too long function name with all namespaces.

**Comment by Neargye** [comment]
`using namespace magic_enum::flags` ?
or
`using namespace yaer = magic_enum::flags`

**Comment by egorodet** [comment]
Yep, it should work with proper alias placement in a common header. Thank you!

**Comment by egorodet** [comment]
Yep, it should work with proper alias placement in a common header. Thank you!
