### ISSUE TITLE
No MinGW support

### ISSUE THREAD

**Issue by githubuser0xFFFF** [Neargye/magic_enum#67]
Hi,

I just tried to compile a library that used your magic_enum library with the current MinGW 64 version 8.1.0. The compilation failed because magic_enum does not propwerly support current MinGW 64 compiler. The version 8.1.0 is the latest official release and also the version that ships with Qt. So this is the version that can be considered stable. 

Would be great, if it would be possible to use magic_enum with a current MinGW compiler.

Apart from that magic_enum is a great library and it is great that you made it available on GitHub.

**Comment by Neargye** [comment]
Hi, unfortunately, I cannot add support for MingW below `9.*` because the only GCC above version 9 is supported. Also, look at #51

**Comment by githubuser0xFFFF** [comment]
Ok, thank you for the response.  Then I hope an official MinGW 9.x release will come out soon.
