### ISSUE TITLE
MAGIC_ENUM_SUPPORTED_ALIASES & magic_enum::enum_values<>()

### ISSUE THREAD

**Issue by Bktero** [Neargye/magic_enum#68]
Hello,

I wanted to write a piece of code that checks that all the values in an enum are unique.

Looking at the [limitations of `magic_enum`](https://github.com/Neargye/magic_enum/blob/master/doc/limitations.md),  I read that "`magic_enum` won't work if a value is aliased". Well, that's what I want to do: detect if at least one value is aliased in my enum.

During my tests, I wrote the following code:

```cpp
enum class Color {
	RED = 8, BLUE = 4, GREEN = 8
};

int main() {
#ifdef MAGIC_ENUM_SUPPORTED_ALIASES
	std::cout << "supported " << MAGIC_ENUM_SUPPORTED_ALIASES << '\n';
#else
	std::cout << "NOT supported" << '\n';
#endif

	auto colors = magic_enum::enum_values<Color>();

	for (auto& color:colors) {
		using namespace magic_enum::ostream_operators;
		std::cout << color << '\n';
	}

	return colors.size();
}
```

It prints:

```
supported 1
BLUE
RED
```

The problem is visible with Compiler Explorer using gcc 10.2: https://godbolt.org/z/4TTerr

The aliased value GREEN doesn't appears in the list returned by `enum_values<Color>()`.

This seems to be a bug because MAGIC_ENUM_SUPPORTED_ALIASES is defined to be 1.

Am I missing something?

**Comment by Neargye** [comment]
`MAGIC_ENUM_SUPPORTED_ALIASES ` macro says that aliases are generally supported.

if `MAGIC_ENUM_SUPPORTED_ALIASES` is set to 0, this behavior will occur
```
supported 0
BLUE
```

**Comment by Neargye** [comment]
In https://godbolt.org/z/4TTerr no bugs, bug is that the name of the macro is a little wrong.

**Comment by Bktero** [comment]
Oh ok!

I was expecting:

```
supported 1
GREEN
BLUE
RED
```

I don't think the name of the macro is wrong, I think that the documentation is just incomplete. Maybe adding a more complete example will help? Maybe, the one we have in this issue?

**Comment by Neargye** [comment]
Yes, I will improve the documentation and then close these issues.
