### ISSUE TITLE
instantiating fold expression with 257 arguments exceeded expression nesting limit of 256

### ISSUE THREAD

**Issue by uikilin100** [Neargye/magic_enum#69]
Hi,

magic_enum/include/magic_enum/magic_enum.hpp:411:71: fatal error: instantiating fold expression with 257 arguments exceeded expression nesting limit of 256
  constexpr std::size_t count = (static_cast<std::size_t>(valid[I]) + ...);
                                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~

How could I fix this compile error?

**Comment by Neargye** [comment]
@uikilin100  could you please test this?
[magic_enum_try_fix69.zip](https://github.com/Neargye/magic_enum/files/5724224/magic_enum_try_fix69.zip)

**Comment by Neargye** [comment]
will be fixed in v0.7.2

**Comment by cr-galrosen** [comment]
Hi @Neargye,
My compilation failed on this error with version 0.66 using clang compiler version 13.0.0.
Any idea?

**Comment by Neargye** [comment]
@cr-galrosen  I think need to update the library

**Comment by cr-galrosen** [comment]
I think that I tried with version 0.73 and got the same error message.

**Comment by cr-galrosen** [comment]
My mistake. I test it again and it was fixed in 0.72.
Thanks.
