### ISSUE TITLE
Fail loud on exceeded range

### ISSUE THREAD

**Issue by mateuszzz88** [Neargye/magic_enum#71]
Currently when my enum is to big for magic_enum and I use `enum_name`, empty string is returned. 
It would be better if magic_enum detected it and threw exception instead.
It would be best if it instead refused to compile. 
https://godbolt.org/z/TTMx1v
```
#include <iostream>
#include "https://raw.githubusercontent.com/Neargye/magic_enum/master/include/magic_enum.hpp"

enum class Color1 {
	RED = 0, BLUE = 4, GREEN = 800 // beyond standard range
};
enum class Color2 {
	RED = 0, BLUE = 4, GREEN = 800000 // beyond max range
};

int main() {
    std::cout <<"[" << magic_enum::enum_name(Color1::GREEN) <<"]" << std::endl;
    std::cout <<"[" << magic_enum::enum_name(Color2::GREEN) <<"]" << std::endl;
    return 0;
}
```
Prints
```
[]
[]
```
Should fail to compile or throw

**Comment by Neargye** [comment]
> throw exception

I would not want to add throwing exceptions, because this will break the code that works with checks, for example, serialization, which works faster without exceptions.


I would advise you to add your own wrapper on top of the existing functions.
```cpp
template <typename E>
std::string_view enum_name(E value) {
  const auto name = magic_enum::enum_name(value);
  if (name .empty()) {
    throw std::runtime_error("enum value does not have name ");
  }
  return name;
}

**Comment by Neargye** [comment]
> Should fail to compile

Unfortunately, this is not possible, such are the limitations of the library.
