### ISSUE TITLE
Feature Request: optimal_index_type -- smallest size data type able to represent all possible valid indexes of an enum

### ISSUE THREAD

**Issue by anadon** [Neargye/magic_enum#74]
In order to limit memory required to access enum values, a convenience function to get the smallest datatype able to represent all valid indexes for an enum from uint8_t, uint16_t, uint32_t, and uint64_t would be nice.

SO has a relevant page: https://stackoverflow.com/questions/7038797/automatically-pick-a-variable-type-big-enough-to-hold-a-specified-number

C++ number standards: https://en.cppreference.com/w/cpp/types/integer

I could do this one, but figure I should ask before I submit a PR out of nowhere.

**Comment by Neargye** [comment]
https://github.com/Neargye/magic_enum/blob/master/include/magic_enum.hpp#L488
It seems to me that something like this has already been done.

But if you find places where you can still optimize, please submit PR.
