### ISSUE TITLE
set MAGIC_ENUM_RANGE_MAX  higher than 1023

### ISSUE THREAD

**Issue by MeTest515** [Neargye/magic_enum#77]
Hi there,
I had a close look at this lib and love it so far. However, I have two following questions/issues.

**How to use the full potential of 16 bit?**
It seems that the real Max Range Limit is 2^10 - 1. As soon you set  #define MAGIC_ENUM_RANGE_MAX 1024 Following error message is shown:

- C1202:" recursive type or function dependency context too complex"
Linked to Line 442 in magic_enum.hpp
Note: I used #pragma warning(push) & #pragma warning(disable : 4244)
 
I also tried useing enum Direction (Line 51) from https://github.com/Neargye/magic_enum/blob/master/test/test_flags.cpp and use enum_cast or enum_name with no success. I receive following error:
C2975 '_Test': invalid template argument for 'std::conditional_t', expected compile-time constant expression
I also used code exactly like it is on Line 374-376.
 
**Why not using 32 bit?**
Beside from the above issue, I tired to replace all (u)int16_t with (u)int32_t and everything looks fine so far, as long the max range is not set at 1024 or above. Is there a specific reason not to do this?
 
PS: I’m mainly using enum_name or enum_cast.

Thank you so much for your work.

**Comment by Neargye** [comment]
https://wandbox.org/permlink/G0RI3GkXGvJzNHET I checked the problem and could not get the error.

Also, for enum-flags use the API from the namespace magic_enum::flags

**Comment by DevonReynolds** [comment]
This seems to be an issue with visual studio 2017.  Attached is a simple project that won't compile in 2017 but will compile in 2019.  I have also tried to compile it using GCC and it works fine.  The number that is fails on doesn't seem to be the same as the original user.  If I set it to 700 it works fine.  If I change it to 1000 it gives me the same error as the original user.
[ConsoleApplication10.zip](https://github.com/Neargye/magic_enum/files/6305058/ConsoleApplication10.zip)

**Comment by miyanyan** [comment]
> This seems to be an issue with visual studio 2017. Attached is a simple project that won't compile in 2017 but will compile in 2019. I have also tried to compile it using GCC and it works fine. The number that is fails on doesn't seem to be the same as the original user. If I set it to 700 it works fine. If I change it to 1000 it gives me the same error as the original user. [ConsoleApplication10.zip](https://github.com/Neargye/magic_enum/files/6305058/ConsoleApplication10.zip)

I got the error when set range [0, 10000] while [0, 1000] works fine if using msvc2017
