### ISSUE TITLE
Stop use of `using` in header. 

### ISSUE THREAD

**Issue by gcamp** [Neargye/magic_enum#80]
The `using` keyword in a header can create conflicts in other headers when magic_enum is imported : 

```
  /usr/bin/../lib/gcc/x86_64-linux-gnu/9/../../../../include/c++/9/optional:656:11: note: candidate found by name lookup is 'std::optional'
1406
      class optional
1407
            ^
1408
  ../magic_enum/include/magic_enum.hpp:99:1: note: candidate found by name lookup is 'magic_enum::optional'
1409
  using optional = std::optional<T>;
```

It would be preferable to use a `typedef` or a macro to define an other type that would be used elsewhere in the code. 

If you agree I can make a PR.

**Comment by andrei-pavel** [comment]
typedefs also leak outside the header. You can just as well use an `using` declaration with your scenario. typedefs also can't be templated which might be a problem in this situation.
```
template <typename T>
using my_optional = std::optional<T>;

[...]

my_optional<int> i(42);
```
There you go.

**Comment by gcamp** [comment]
Typedefs also leaks but they can named in a unique way. You're right however about templates. 

I could indeed use the value defined by msg_pack but I don't like having my code assuming things added by a library. Currently need to change dozens of file because I updated magic_enum, which is far from perfect. (currently need to update because of https://github.com/Neargye/magic_enum/issues/69).

**Comment by Neargye** [comment]
Hi @gcamp, fix in master, it's still allowed to add an alias if someone needs it, but not leaks by default.
Could you please check this fix?

**Comment by gcamp** [comment]
Working for me! Thanks for the quick fix
