### ISSUE TITLE
cmake "bug" about header only library

### ISSUE THREAD

**Issue by Flow86** [Neargye/magic_enum#83]
Hi,

in the code lines

https://github.com/Neargye/magic_enum/blob/8deb7f96e74e62cd1d9fd8920debfbe27f4bb8d1/CMakeLists.txt#L33-L35

the package config is generated.

I thought magic_enum is a header only library but the package config file generated in those lines still has an architecture check active, which will cause

```
The following configuration files were considered but not accepted:
1> [CMake] 
1> [CMake]     C:/Code/magic_enum/install/lib/cmake/magic_enum/magic_enumConfig.cmake, version: 0.7.2 (64bit)
```
when trying to use the same install for a 32bit build.

only adding `ARCH_INDEPENDENT` to the `write_basic_package_version_file` disables this check.

**Comment by Neargye** [comment]
Hi @Flow86, Do you have any suggestions and how to correct theшы issue?

**Comment by Flow86** [comment]
the flag `ARCH_INDEPENDENT ` is new in cmake 3.14 which does exactly correct that issue. 

so adding it to lines https://github.com/Neargye/magic_enum/blob/8deb7f96e74e62cd1d9fd8920debfbe27f4bb8d1/CMakeLists.txt#L33-L35 does suffice, but you would need to set minimum cmake version to 3.14

```cmake
write_basic_package_version_file(${PROJECT_NAME}ConfigVersion.cmake 
                   VERSION ${PROJECT_VERSION} 
                   COMPATIBILITY AnyNewerVersion ARCH_INDEPENDENT)
```
