### ISSUE TITLE
try online with Compiler Explorer

### ISSUE THREAD

**Issue by gchoinka** [Neargye/magic_enum#9]
As an alternative to wandbox 
https://godbolt.org/z/lX6L-B

to get the hash for the include link just go to the file and press the y key

**Comment by Neargye** [comment]
Hm, 
```
#include "https://raw.githubusercontent.com/Neargye/magic_enum/f5ef718120d5937d9051c7e9f7d48a4cc5b6b6df/include/magic_enum.hpp"
````
did not think about it earlier, funny.

**Comment by Neargye** [comment]
add to reamde https://github.com/Neargye/magic_enum/commit/a9f8797ff2ccff4f025ecd767e25beccb4090b6b
