### ISSUE TITLE
Check that all enums actually fit in [MAGIC_ENUM_RANGE_MIN, MAGIC_ENUM_RANGE_MAX] range

### ISSUE THREAD

**Issue by mathbunnyru** [Neargye/magic_enum#91]
For example, I have a code like this:

```
enum Values { Value1 = 1, Value2 = 10, Value3 = 100, Value4 = 1000 };
```

Code like this will silently compile and run (though it shouldn't), but it's a current limitation of max enum value:

```
EXPECT_EQ(magic_enum::enum_count<Values>(), 3);
EXPECT_EQ(magic_enum::enum_cast<Values>("Value4"), std::nullopt);
```

What I propose:

Add 2 functions: `enum_min_value<Enum>` and `enum_max_value<Enum>` - they can be useful by themselves.
Is it possible to implement them without limitations?
**I do not know if it's possible or not** :(

And then in all functions check that `MAGIC_ENUM_RANGE_MIN <= enum_min_value` and the same for max value.

**Comment by mathbunnyru** [comment]
I think this is impossible with the current approach (otherwise you would have already implemented it) :(

**Comment by Neargye** [comment]
unfortunately, this is a limitation of this library
