### ISSUE TITLE
`enum_name` returns error name with the suffix 'W'

### ISSUE THREAD

**Issue by shelllet** [Neargye/magic_enum#92]
Enum defined:
```
 enum class Tags : int32_t
    {
        FindWindow= 0,
    };
```
called:
`magic_enum::enum_name(d.TagName())` return `FindWindowW`;

I think it's because i included the "Windows.h" header file.

**Comment by Neargye** [comment]
In Window.h

```cpp
#ifdef UNICODE
#define FindWindow  FindWindowW
#else
#define FindWindow  FindWindowA
#endif // !UNICODE
```

**Comment by Neargye** [comment]
I honestly don't know how to get around this problem, except how not to include the header WIndow.h

**Comment by shelllet** [comment]
thks, `#undef FindWindow` can resolve this, may be this is `macro` normal question.
