### ISSUE TITLE
Enum entries with non-ascii characters get removed

### ISSUE THREAD

**Issue by Emill** [Neargye/magic_enum#94]
```C++
enum Siffra {
    ETT,
    TVÅ,
    TRE
};
```

This code works fine in gcc and clang, but when using magic_enum with it, it only detects `ETT` and `TRE`.

It seems the `pretty_name` function in magic_enum only allows `0-9`, `a-z`, `A-Z` and `_`. Annex E in the C++ standard seems to allow these kind of characters in identifiers.

FYI, `__PRETTY_FUNCTION__` includes this for TVÅ: `[E = Siffra, V = TV\303\205]`.

**Comment by Neargye** [comment]
Fixed #95
