### ISSUE TITLE
 static_assert failed due to requirement 'detail::count_v<TestEnum, false> > 0'

### ISSUE THREAD

**Issue by morph208** [Neargye/magic_enum#96]
Hello,

I have a compilation issue with magic_enum::enum_cast using a string as input with the compiler clang 12.0.1. More precisely I am using enum_cast to cast a string into an enum into 2 locations in my code, one was compiling fine but not the others. It took me a while to discover the cause.

We are using the library g3log for our logs and I realised that if the header [g3log.hpp](https://github.com/KjellKod/g3log/blob/1.3.4/src/g3log/g3log.hpp) was included before magic_enum.hpp, the call to emum_cast does not compile. 

More specifically, this is the piece of code causing the issue with magic_enum: 

```
#if !defined(__PRETTY_FUNCTION__)
#define __PRETTY_FUNCTION__   __FUNCTION__
#endif
```

You can see a reproductible code here: https://godbolt.org/z/dEnf1Gq56. 

I am not very familiar with __PRETTY_FUNCTION__ but I would have expected it to be defined with clang. It seems not to be the case for some reason so it is defined with __FUNCTION__ and I'm guessing that magic_enum has a problem with that. At first glance it does not seem too crazy for g3log to define __PRETTY_FUNCTION__  if it does not exist.

And if it is not defined, why magic_enum compiles successfully since magic_enum makes use of it? 

I am not sure who is at fault here, g3log or magic_enum, but there are definitely not working together with clang. What is your take on that? Thank you in advance for your help.

**Comment by Neargye** [comment]
Hm, add `#undef __PRETTY_FUNCTION__` work https://godbolt.org/z/bd4P6Y64P

**Comment by Neargye** [comment]
You can make a quick patch to the magic_enum, just add in heder `#undef __PRETTY_FUNCTION__`, it's should work https://godbolt.org/z/bd4P6Y64P.

But I'm not sure if it's worth adding this directly to the library, it looks rather strange.

**Comment by morph208** [comment]
Thanks for your quick reply. I know it looks strange, that's why I was interested into your take on that. I am planning to add

```
#if defined( __clang__ )
#    undef __PRETTY_FUNCTION__
#endif
```

before including magic_enum header in my code. I need to be able to compile with visual studio too so a general undef does not work. But if __PRETTY_FUNCTION__ is not defined by clang (and I read the opposite everywhere), why magic_enum compiles with clang using __PRETTY_FUNCTION__ that is not defined. It seems that I am missing something...

**Comment by Neargye** [comment]
I think the problem here is that __PRETTY_FUNCTION__ is not a macro, it's [magic constants](https://gcc.gnu.org/onlinedocs/gcc/Function-Names.html)

**Comment by morph208** [comment]
> I think the problem here is that `__PRETTY_FUNCTION__` not a macro, it's [magic constants](https://gcc.gnu.org/onlinedocs/gcc/Function-Names.html)

I stumbled accross this page. Yeah maybe the test `defined(__PRETTY_FUNCTION__)` is not valid since it is not a macro...
