### ISSUE TITLE
Remove prefix from enum name

### ISSUE THREAD

**Issue by ysc3839** [Neargye/magic_enum#97]
When working with third-party libraries, there's enums like:
```
enum class Color {
  kRed = 2,
  kBlue = 4,
  kGreen = 8
};
```
```
enum Color {
  COLOR_RED = 2,
  COLOR_BLUE = 4,
  COLOR_GREEN = 8
};
```

Is there an option to remove the prefix ("k" or "COLOR_")?

**Comment by lakeweb** [comment]
Here is what I did, and it just may make sense. With the enums staring with 'e', I wanted the strings without the 'e'
enum the_mode {
  enull,
  eopen,
  enew,
  ecopy,
  erename,
  edelete,
  emove,
};
//where the_mode mode; is a member of projectmng_state

projectmng_state::the_mode _projectmng_state::get_mode(const std::string& pstr) {
	auto ret = magic_enum::enum_cast<the_mode>('e' + pstr); return ret.has_value() ? ret.value() : enull; }

const char* _projectmng_state::get_modestr() { auto ret = magic_enum::enum_name(mode); return ret.data() ? ret.data() + 1 : "error"; }

**Comment by durka** [comment]
Can this be reopened? I am working with a lot of enums from a C library that are defined with the name of the enum type as a prefix. Some of them are bitflags, so cleaning up myself after calling `enum_flags_name` is cumbersome and slow.

It would be nice if I could set a boolean in `magic_enum::customize::enum_range` for a prefix to remove.

**Comment by Neargye** [comment]
@durka Hi, please create new one
