### ISSUE TITLE
compile error in debug mode @ VS2019 C++17

### ISSUE THREAD

**Issue by segatecm** [Neargye/magic_enum#98]
Hi,
I use magic enum in vs2019. 
At release mode, it works fine.
but debug mode, compiled error:

1>D:\Work\XiaoKCapture\XiaoKMulti\magic_enum.hpp(448,40): error C2131: expression did not evaluate to a constant
1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30037\include\xstring(1364,9): message : failure was caused by evaluation exceeding step limit of 1048576 (/constexpr:steps<NUMBER>)
1>D:\Work\XiaoKCapture\XiaoKMulti\magic_enum.hpp(474): message : see reference to function template instantiation 'auto magic_enum::detail::values<E,false,-128,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27 
...

**Comment by Neargye** [comment]
Could you provide a minimal example of an error?

**Comment by segatecm** [comment]
define MAGIC_ENUM_RANGE_MAX 10000 -> I make this change
```cpp
enum class VideoFormat {
	Any,
	Unknown,

	/* raw formats */
	ARGB = 100,
	XRGB,

	/* planar YUV formats */
	I420 = 200,
	NV12,
	YV12,
	Y800,

	/* packed YUV formats */
	YVYU = 300,
	YUY2,
	UYVY,
	HDYC,

	/* encoded formats */
	MJPEG = 400,
	H264,
};
int main()
{
	VideoFormat f = VideoFormat::MJPEG;
	magic_enum::enum_name(f);
}
```

**Comment by Neargye** [comment]
`failure was caused by evaluation exceeding step limit of 1048576 (/constexpr:steps)`

The error says that there are too many calculations at the compilation stage.
Try to increase the number of steps through the compiler settings `/constexpr:steps` or do not set such a large `MAGIC_ENUM_RANGE_MAX`.

**Comment by segatecm** [comment]
oh, Thanks.
Why it not happend in release mode?

**Comment by Neargye** [comment]
As I know in the debug mode, some debug objects are used when creating STL containers, this may be the problem.

**Comment by segatecm** [comment]
Thanks!
