### ISSUE TITLE
Breakpoints fail with include - Microsoft Visual C++ 2019 v 16.11.1

### ISSUE THREAD

**Issue by lakeweb** [Neargye/magic_enum#99]
Weirdest thing, just including "magic_enum.hpp" and breakpoints fail to work. Comment the include and breakpoints work fine. Other than that, I think this is a brilliant library! But how can I use it if I loose the use of breakpoints? Do you think I should take this to the Microsoft Community?
Microsoft Visual C++ 2019 v 16.11.1
ISO C++20 Standard (/std:c++20)

**Update**
So, i dropped this into my big project. Not an issue as far as breakpoints go. The issue was in a small console app to test. I'll see if I can whittle it down to a minimal that reflects the issue.

**Last Update**
For what ever reason, if you include this file before magic_enum.hpp, the breakpoints stop working! Just in the case someone else runs into this kind of thing...
https://lakeweb.net/public/csv_parse.h
(10 years old, really needs a rewrite)

**Comment by Neargye** [comment]
Unfortunately, I have no idea yet why this could happen.
